In [1]:
## Installing Selenium library
!pip install selenium

Requirement already satisfied: selenium in c:\users\swati\anaconda3\lib\site-packages (4.1.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\swati\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\swati\anaconda3\lib\site-packages (from selenium) (1.26.4)
Requirement already satisfied: trio~=0.17 in c:\users\swati\anaconda3\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: sniffio in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: cffi>=1.14 in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.5)
Requirement already satisfied: outcome in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sortedcontainers in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\swati\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: pycparser in c:\users\swati\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\swati\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\swati\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (3.4.7)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\swati\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (20.0.1)
Requirement already satisfied: certifi in c:\users\swati\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2020.12.5)
Requirement already satisfied: six>=1.5.2 in c:\users\swati\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\swati\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)

In [1]:
## Importing necessary libraries:-
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")

# 1.Scraapping Data for Data Analyst for loaction Bangalore

In [2]:
## Connect to the driver : -
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [3]:
## Get the specific url to the driver
driver.get("https://www.naukri.com/")

In [4]:
## Finding element for job search
search_jobs =driver.find_element_by_id("qsb-keyword-sugg")
search_jobs.send_keys("Data Analyst")
search_loc = driver.find_element_by_id("qsb-location-sugg")
search_loc.send_keys("Bangalore")

In [5]:
## Finding element for Search button
search_button = driver.find_element_by_xpath("//div[@class = 'search-btn']/button")
search_button.click()

In [6]:
## Now Creating empty lists for Job -Title,Location,Company Name,Experience Required:
Job_Title = []
location =[]
company_name =[]
exp =[]

In [34]:
## Scrapping Job Title :
job_title_tag = driver.find_elements_by_xpath("//a[@class ='title fw500 ellipsis']")

#job_title_tag[:10]

for i in job_title_tag:
    Job_Title.append(i.text)
print("****** Job Title****************")    
#print(Job_Title)    
Job_Title =Job_Title[0:2] +Job_Title[20:28]
print(Job_Title)
print(len(Job_Title))
print("*********************************")

#### Scrapping Location
#search_location = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
search_location = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")
#search_location[:10]
for i in search_location:
    location.append(i.text)
print("********** Location*************")  
#print(location)
location = location[0:2]+location[20:28]
print(location)
print(len(location))
print("********************************")    

### Scrapping Company Name :-
company = driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
for i in company:
    company_name.append(i.text)
    
print("********** Company Name *************")        
company_name=company_name[0:2]+company_name[20:28]
print(len(company_name))
print(company_name)
print(len(company_name))

print("********************************")    

## Scrapping Experience Required : 
exp_req = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
for i in exp_req:
    exp.append(i.text)
    
print("********** Experience Required *************")        
exp = exp[0:2]+exp[20:28]    
print(exp)
print(len(exp))
print("********************************")    


data_analyst_df = pd.DataFrame({})
data_analyst_df['Job Title'] = Job_Title
data_analyst_df['Location'] = location
data_analyst_df['Company Name'] = company_name
data_analyst_df['Experience Required'] = exp


data_analyst_df

****** Job Title****************
['Assistant/deputy Manager - Geo-spatial Data Analyst', 'Senior Data Analyst', 'Data Analyst', 'Hiring Business Data Analyst +ETL- Tech Mahindra, Bangalore', 'Business Analyst / Data Analyst', 'Senior Data Analyst', 'Job Opportunity For Clinical Data Analyst - CDM', 'Data Analyst', 'Data Analyst', 'Financial Data Analyst']
10
*********************************
********** Location*************
['Gurgaon/Gurugram, bangalore', 'Bangalore/Bengaluru', 'Bangalore/Bengaluru', 'Bangalore/Bengaluru', 'Bangalore/Bengaluru\n(WFH during Covid)', 'Bengaluru/Bangalore', 'Kolkata, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)\n(WFH during Covid)', 'Bangalore/Bengaluru', 'Bangalore/Bengaluru', 'Hyderabad/Secunderabad, Chennai, Bangalore/Bengaluru']
10
********************************
********** Company Name *************
10
['Maruti Suzuki India', 'Rapido', 'Slice', 'Tech Mahindra', 'GetSimpl', 'Flipkart', 'Paradigm IT', 'Ola Cabs', 'ExecBoardinAsia', 'UnitedLex']
10
********************************
********** Experience Required *************
['3-5 Yrs', '1-6 Yrs', '0-2 Yrs', '6-10 Yrs', '2-4 Yrs', '4-5 Yrs', '3-8 Yrs', '1-3 Yrs', '5-10 Yrs', '2-5 Yrs']
10
********************************

,Job Title,Location,Company Name,Experience Required
0,Assistant/deputy Manager - Geo-spatial Data An...,"Gurgaon/Gurugram, bangalore",Maruti Suzuki India,3-5 Yrs
1,Senior Data Analyst,Bangalore/Bengaluru,Rapido,1-6 Yrs
2,Data Analyst,Bangalore/Bengaluru,Slice,0-2 Yrs
3,Hiring Business Data Analyst +ETL- Tech Mahind...,Bangalore/Bengaluru,Tech Mahindra,6-10 Yrs
4,Business Analyst / Data Analyst,Bangalore/Bengaluru\n(WFH during Covid),GetSimpl,2-4 Yrs
5,Senior Data Analyst,Bengaluru/Bangalore,Flipkart,4-5 Yrs
6,Job Opportunity For Clinical Data Analyst - CDM,"Kolkata, Hyderabad/Secunderabad, Pune, Chennai...",Paradigm IT,3-8 Yrs
7,Data Analyst,Bangalore/Bengaluru,Ola Cabs,1-3 Yrs
8,Data Analyst,Bangalore/Bengaluru,ExecBoardinAsia,5-10 Yrs
9,Financial Data Analyst,"Hyderabad/Secunderabad, Chennai, Bangalore/Ben...",UnitedLex,2-5 Yrs

# 2.Scrapping data for Data Scientist job position in Bangalore

In [33]:
driver.close()

In [34]:
## Connect to the driver : -
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [35]:
## Get the specific url to the driver
driver.get("https://www.naukri.com/")

In [36]:
## Finding element for job search
search_jobs =driver.find_element_by_id("qsb-keyword-sugg")
search_jobs.send_keys("Data Scientist")
search_loc = driver.find_element_by_id("qsb-location-sugg")
search_loc.send_keys("Bangalore")

In [37]:
## Finding element for Search button
search_button = driver.find_element_by_xpath("//div[@class = 'search-btn']/button")
search_button.click()

In [38]:
### making empty list for Job Title,Job Location,Company Name 
job_title =[]
job_location =[]
company_name =[]
###Scrapping Job Title :-
title = driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in title:
    job_title.append(i.text)
print("*********** Job Title*****************")    
print(job_title[:10]) 
print("***************************************")

## Scrapping Job Location:-
loc = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in loc:
    job_location.append(i.text)
print("***************Job Location************")    
print(job_location[:10])   
print("****************************************")

## Scrapping Company Name
com_name = driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
for i in com_name:
    company_name.append(i.text)
print("*************** Company Name****************")    
print(company_name[:10])    
print("*******************************************")

### Making DataFrame :-
Data_Scientist_df = pd.DataFrame({ 'Job Title' : job_title[:10],
                                   'Job Location': job_location[:10],
                                   'Company Name' : company_name[:10]
                                 })
Data_Scientist_df

*********** Job Title*****************
['Lead/Senior Data Scientist (NLP)', 'Data Scientist: Advanced Analytics', 'Senior Engineer - AIML - Data Scientist', 'Lead Data Scientist', 'Jr. Data Analyst/ Jr. Data Scientist', 'Senior Data Scientist', 'Cognitive/AI Senior Data Scientist', 'Senior Data Scientist', 'Lead Programmer - Data Scientist', 'Senior Data Scientist']
***************************************
***************Job Location************
['Bangalore/Bengaluru', 'Bengaluru/Bangalore', 'Bangalore/Bengaluru', 'Palani, Bangalore/Bengaluru', 'Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)', 'Pune, Bangalore/Bengaluru, Delhi / NCR', 'Bengaluru/Bangalore', 'Kolkata, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)', 'Bangalore/Bengaluru', 'Bangalore/Bengaluru']
****************************************
*************** Company Name****************
['Samya.AI A FRACTAL Entity', 'IBM India Pvt. Limited', 'Unisys', 'Groww', 'Sejal Consulting Hub', 'Wipro', 'IBM India Pvt. Limited', 'Wipro', 'GlaxoSmithKline Pharmaceuticals Limited', 'Juniper Networks']
*******************************************

,Job Title,Job Location,Company Name
0,Lead/Senior Data Scientist (NLP),Bangalore/Bengaluru,Samya.AI A FRACTAL Entity
1,Data Scientist: Advanced Analytics,Bengaluru/Bangalore,IBM India Pvt. Limited
2,Senior Engineer - AIML - Data Scientist,Bangalore/Bengaluru,Unisys
3,Lead Data Scientist,"Palani, Bangalore/Bengaluru",Groww
4,Jr. Data Analyst/ Jr. Data Scientist,"Hyderabad/Secunderabad, Bangalore/Bengaluru, M...",Sejal Consulting Hub
5,Senior Data Scientist,"Pune, Bangalore/Bengaluru, Delhi / NCR",Wipro
6,Cognitive/AI Senior Data Scientist,Bengaluru/Bangalore,IBM India Pvt. Limited
7,Senior Data Scientist,"Kolkata, Hyderabad/Secunderabad, Pune, Chennai...",Wipro
8,Lead Programmer - Data Scientist,Bangalore/Bengaluru,GlaxoSmithKline Pharmaceuticals Limited
9,Senior Data Scientist,Bangalore/Bengaluru,Juniper Networks

In [35]:
driver.close()

# 2.Scrapping data using Location and Salary Filter

In [39]:
### Scrapping data using Location and Salary Filter:
## Connect to the driver : -
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [40]:
## Get the specific url to the driver
driver.get("https://www.naukri.com/")

In [41]:
## Finding element for job search
search_jobs =driver.find_element_by_id("qsb-keyword-sugg")
search_jobs.send_keys("Data Scientist")

In [42]:
## Finding element for Search button
search_button = driver.find_element_by_xpath("//div[@class = 'search-btn']/button")
search_button.click()

In [43]:
## Making empty lists for Job Title,Job Location,Company Name and experience required :-
Job_Title = []
location =[]
company_name =[]
exp =[]

title_tags = driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
for i in title_tags:
    Job_Title.append(i.text)
print("***********Job Title************")    
print(Job_Title[:10])    
print("********************************")

loc = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']/span[1]")
for i in loc:
    location.append(i.text)
print("***********Job Title************")        
print(location[:10] ) 
print("*****************************")

comp_name = driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
for i in comp_name:
    company_name.append(i.text)
print("******* Company Name*****************")   
print(company_name[:10])
print("*************************************")

exp_reqd = driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']/span[1]")
for i in exp_reqd:
    exp.append(i.text)
print("***************** Experience************")  
print(exp[:10])
print("****************************************")

df = pd.DataFrame({})
df['Job Title'] = Job_Title[:10]
df['Job Location'] = location[:10]
df['Company Name'] = company_name[:10]
df['Experience Required'] = exp[:10]

df

***********Job Title************
['Data Scientist', 'Jr. Data Analyst/ Jr. Data Scientist', 'Data Scientist', 'Data Scientist: Advanced Analytics', 'Lead/Senior Data Scientist (NLP)', 'Data Scientist | Senior Data Scientist', 'Senior Engineer - AIML - Data Scientist', 'Senior Data Scientist', 'Cognitive/AI Senior Data Scientist', 'Senior Data Scientist']
********************************
***********Job Title************
['Noida, New Delhi, Faridabad, Gurgaon/Gurugram, Delhi / NCR', 'Hyderabad/Secunderabad, Bangalore/Bengaluru, Mumbai (All Areas)', 'Panaji/Panjim', 'Bengaluru/Bangalore', 'Bangalore/Bengaluru', 'Delhi / NCR, DelhiNCR', 'Bangalore/Bengaluru', 'Pune, Bangalore/Bengaluru, Delhi / NCR', 'Bengaluru/Bangalore', 'Kolkata, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)']
*****************************
******* Company Name*****************
['LG Electronics India Pvt. Ltd.', 'Sejal Consulting Hub', 'Siemens Limited', 'IBM India Pvt. Limited', 'Samya.AI A FRACTAL Entity', '4bell Technology', 'Unisys', 'Wipro', 'IBM India Pvt. Limited', 'Wipro']
*************************************
***************** Experience************
['0-2 Yrs', '0-5 Yrs', '0-5 Yrs', '5-7 Yrs', '3-8 Yrs', '6-11 Yrs', '4-9 Yrs', '4-9 Yrs', '4-8 Yrs', '5-10 Yrs']
****************************************

,Job Title,Job Location,Company Name,Experience Required
0,Data Scientist,"Noida, New Delhi, Faridabad, Gurgaon/Gurugram,...",LG Electronics India Pvt. Ltd.,0-2 Yrs
1,Jr. Data Analyst/ Jr. Data Scientist,"Hyderabad/Secunderabad, Bangalore/Bengaluru, M...",Sejal Consulting Hub,0-5 Yrs
2,Data Scientist,Panaji/Panjim,Siemens Limited,0-5 Yrs
3,Data Scientist: Advanced Analytics,Bengaluru/Bangalore,IBM India Pvt. Limited,5-7 Yrs
4,Lead/Senior Data Scientist (NLP),Bangalore/Bengaluru,Samya.AI A FRACTAL Entity,3-8 Yrs
5,Data Scientist | Senior Data Scientist,"Delhi / NCR, DelhiNCR",4bell Technology,6-11 Yrs
6,Senior Engineer - AIML - Data Scientist,Bangalore/Bengaluru,Unisys,4-9 Yrs
7,Senior Data Scientist,"Pune, Bangalore/Bengaluru, Delhi / NCR",Wipro,4-9 Yrs
8,Cognitive/AI Senior Data Scientist,Bengaluru/Bangalore,IBM India Pvt. Limited,4-8 Yrs
9,Senior Data Scientist,"Kolkata, Hyderabad/Secunderabad, Pune, Chennai...",Wipro,5-10 Yrs

In [44]:
driver.close()

# 3.Scrapping  Sun Glasses Data from Flip Cart

In [36]:
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [37]:
## specifying the url to get sunglasses data
driver.get("https://www.flipkart.com/")
#driver.get("https://www.flipkart.com/search?q=sun+glasses&sid=26x&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&as-pos=1&as-type=RECENT&suggestionId=sun+glasses%7CSunglasses&requestId=1542941d-3976-48a3-a353-2330fb313880&as-searchtext=Sun+Glasees+&page=1")

In [39]:
##Finding xpath  for searching sunglasse
search_product = driver.find_element_by_xpath("//input[@class='_3704LK']")
search_product.send_keys("Sunglasses")

In [ ]:
##  finding xpath for clicking seach
search_click = driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_click.click()

In [94]:
### Creating empty lists for Brand,Product Description,price and discount 
Brand =[]
product_desc =[]
price =[]
discount =[]
## Scrapping First 40 Brand Name
brand = driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for i in brand:
    Brand.append(i.text)
print("-------------Brand Name--------------")    
print(Brand) 
print(len(Brand))
print("---------------------------------------")

## Scrapping Product Description:
desc = driver.find_elements_by_xpath("//a[@class = 'IRpwTa']")

for i in desc:
    product_desc.append(i.text)
print("---------------Product Description------------------")    
print(product_desc)
print("-------------------------------------------")

#### Scrapping Price Data:-
pp = driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for i in pp:
    price.append(i.text)
print("----------Price-------------")    
print(price)    
print("----------------------------")

## SCRAPPING discount data
disc = driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span")
for i in disc:
    discount.append(i.text)
print("----------Discount-------------")    
    
print(discount)  

print("----------------------------")

-------------Brand Name--------------
['NuVew', 'kingsunglasses', 'ROYAL SON', 'Dannilo', 'NuVew', 'Singco India', 'Singco', 'hipe', 'Elligator', 'PHENOMENAL', 'ROYAL SON', 'Singco India', 'Fastrack', 'ROZZETTA CRAFT', 'Elligator', 'Singco', 'DEIXELS', 'Fastrack', 'New Specs', 'Singco India', 'ROYAL SON', 'ROZZETTA CRAFT', 'Silver Kartz', 'ROZZETTA CRAFT', 'kingsunglasses', 'Rich Club', 'Elligator', 'VILLAIN', 'AISLIN', 'AISLIN', 'PHENOMENAL', 'Dannilo', 'PHENOMENAL', 'Fastrack', 'kingsunglasses', 'hipe', 'ROYAL SON', 'SUNBEE', 'Elligator', 'ZOSTAL']
40
---------------------------------------
---------------Product Description------------------
['UV Protection, Night Vision, Riding Glasses Sports Sung...', 'UV Protection Rectangular Sunglasses (55)', 'UV Protection Retro Square Sunglasses (58)', 'Others Round Sunglasses (Free Size)', 'UV Protection, Mirrored Wayfarer Sunglasses (57)', 'Riding Glasses, UV Protection, Others Aviator Sunglasse...', 'UV Protection, Others Aviator Sunglasses (32)', 'Mirrored, UV Protection, Gradient Round Sunglasses (55)', 'UV Protection, Gradient Aviator Sunglasses (53)', 'UV Protection, Mirrored Retro Square Sunglasses (53)', 'UV Protection Round Sunglasses (50)', 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...', 'UV Protection Aviator Sunglasses (Free Size)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection Round Sunglasses (54)', 'UV Protection Aviator Sunglasses (Free Size)', 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...', 'Polarized Retro Square Sunglasses (Free Size)', 'UV Protection Rectangular Sunglasses (Free Size)', 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...', 'UV Protection Retro Square Sunglasses (58)', 'UV Protection Retro Square Sunglasses (Free Size)', 'UV Protection Aviator Sunglasses (88)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection, Mirrored Round Sunglasses (Free Size)', 'UV Protection Round Sunglasses (50)', 'UV Protection, Riding Glasses Rectangular, Retro Square...', 'Others Retro Square Sunglasses (Free Size)', 'UV Protection, Gradient Butterfly, Retro Square Sunglas...', 'Toughened Glass Lens, UV Protection Aviator Sunglasses ...', 'UV Protection, Mirrored Retro Square Sunglasses (Free S...', 'Gradient, Night Vision, Riding Glasses Round, Oval Sung...', 'UV Protection Retro Square Sunglasses (Free Size)', 'UV Protection Wrap-around Sunglasses (Free Size)', 'UV Protection, Night Vision Wayfarer Sunglasses (Free S...', 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...', 'Polarized Rectangular Sunglasses (65)', 'UV Protection, Polarized Wayfarer Sunglasses (Free Size...', 'Mirrored Round Sunglasses (53)', 'UV Protection Wrap-around Sunglasses (Free Size)']
-------------------------------------------
----------Price-------------
['₹240', '₹259', '₹449', '₹188', '₹188', '₹201', '₹289', '₹189', '₹263', '₹299', '₹359', '₹664', '₹719', '₹396', '₹275', '₹189', '₹236', '₹639', '₹188', '₹203', '₹449', '₹325', '₹255', '₹383', '₹249', '₹383', '₹318', '₹549', '₹446', '₹691', '₹319', '₹244', '₹319', '₹719', '₹279', '₹209', '₹664', '₹276', '₹263', '₹168']
----------------------------
----------Discount-------------
['69% off', '82% off', '70% off', '81% off', '82% off', '86% off', '85% off', '87% off', '82% off', '85% off', '76% off', '77% off', '20% off', '82% off', '78% off', '81% off', '60% off', '20% off', '87% off', '70% off', '70% off', '80% off', '78% off', '80% off', '85% off', '61% off', '78% off', '26% off', '70% off', '81% off', '84% off', '83% off', '84% off', '20% off', '83% off', '79% off', '66% off', '78% off', '89% off', '83% off']
----------------------------

In [77]:
### For next 40 data on 2nd page:-
driver.get("https://www.flipkart.com/search?q=sun+glasses&sid=26x&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&as-pos=1&as-type=RECENT&suggestionId=sun+glasses%7CSunglasses&requestId=1542941d-3976-48a3-a353-2330fb313880&as-searchtext=Sun+Glasees+&page=2")

In [80]:
## Scrapping  Sunglasses Next 40 Brand name, Product Description,Price,Discount:-
BrandNext =[] 
product_desc_next =[]
price_next =[]
discount_next =[]


brand_next = driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for i in brand_next:
    BrandNext.append(i.text)
print("-------------Brand Name--------------")    
print(BrandNext) 
print("---------------------------------------")

product_des_next = driver.find_elements_by_xpath("//a[@class = 'IRpwTa']")
for i in product_des_next:
    product_desc_next.append(i.text)
print("-------------Product Description--------------")    
print(product_desc_next) 
print("---------------------------------------")

#### Scrapping Price Data:-
pp_next = driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for i in pp_next:
    price_next.append(i.text)
print("----------Price-------------")    
print(price_next)    
print("----------------------------")

## SCRAPPING discount data
disc_next = driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span")
for i in disc_next:
    discount_next.append(i.text)
print("----------Discount-------------")    
    
print(discount_next)  

print("----------------------------")

-------------Brand Name--------------
['Fastrack', 'kingsunglasses', 'PIRASO', 'Dannilo', 'Fastrack', 'SRPM', 'hipe', 'Singco India', 'PIRASO', 'Johaena', 'Fastrack', 'Singco', 'AISLIN', 'GANSTA', 'hipe', 'Singco India', 'Lee Topper', 'kingsunglasses', 'PIRASO', 'ROZZETTA CRAFT', 'New Specs', 'agera', 'ROZZETTA CRAFT', 'VILLAIN', 'kingsunglasses', 'GANSTA', 'ROZZETTA CRAFT', 'Dannilo', 'Fastrack', 'DEIXELS', 'kingsunglasses', 'ZOSTAL', 'Lee Topper', 'Elligator', 'ROYAL SON', 'Singco India', 'Rich Club', 'PIRASO', 'ROYAL SON', 'Fravy']
---------------------------------------
-------------Product Description--------------
['Gradient, UV Protection Wayfarer Sunglasses (Free Size)', 'Mirrored, UV Protection Aviator Sunglasses (56)', 'UV Protection Butterfly Sunglasses (65)', 'Others Round Sunglasses (Free Size)', 'UV Protection Sports Sunglasses (Free Size)', 'UV Protection Wayfarer Sunglasses (53)', 'Mirrored, UV Protection, Gradient Round Sunglasses (55)', 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...', 'UV Protection, Polarized Aviator Sunglasses (32)', 'Riding Glasses, UV Protection Oval Sunglasses (52)', 'UV Protection Wayfarer Sunglasses (Free Size)', 'UV Protection Aviator Sunglasses (Free Size)', 'UV Protection, Gradient Butterfly, Retro Square Sunglas...', 'UV Protection Aviator Sunglasses (57)', 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...', 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...', 'Riding Glasses, Night Vision Wrap-around Sunglasses (Fr...', 'UV Protection Round Sunglasses (Free Size)', 'UV Protection Aviator Sunglasses (54)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection Rectangular Sunglasses (Free Size)', 'Gradient Aviator Sunglasses (55)', 'UV Protection, Riding Glasses Rectangular Sunglasses (F...', 'Others Retro Square Sunglasses (Free Size)', 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)', 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)', 'UV Protection, Gradient Retro Square Sunglasses (Free S...', 'Gradient, Night Vision, Riding Glasses Round, Oval Sung...', 'UV Protection Wayfarer Sunglasses (55)', 'UV Protection Aviator, Wayfarer Sunglasses (Free Size)', 'UV Protection, Mirrored Round Sunglasses (54)', 'UV Protection Wrap-around Sunglasses (Free Size)', 'UV Protection, Riding Glasses Retro Square, Spectacle ...', 'UV Protection Round Sunglasses (55)', 'UV Protection, Gradient Butterfly Sunglasses (57)', 'Mirrored, UV Protection, Riding Glasses, Others Wrap-ar...', 'UV Protection, Others Round Sunglasses (48)', 'UV Protection Aviator Sunglasses (58)', 'Mirrored Aviator Sunglasses (58)', 'UV Protection, Gradient, Night Vision Retro Square Sung...']
---------------------------------------
----------Price-------------
['₹639', '₹211', '₹336', '₹188', '₹719', '₹220', '₹189', '₹664', '₹164', '₹156', '₹719', '₹189', '₹401', '₹269', '₹209', '₹203', '₹276', '₹279', '₹187', '₹383', '₹169', '₹196', '₹426', '₹549', '₹259', '₹209', '₹349', '₹244', '₹579', '₹202', '₹211', '₹168', '₹375', '₹239', '₹664', '₹279', '₹245', '₹299', '₹359', '₹285']
----------------------------
----------Discount-------------
['20% off', '83% off', '87% off', '81% off', '20% off', '77% off', '87% off', '77% off', '89% off', '87% off', '20% off', '81% off', '73% off', '86% off', '79% off', '70% off', '88% off', '82% off', '88% off', '80% off', '89% off', '82% off', '80% off', '26% off', '87% off', '88% off', '82% off', '83% off', '27% off', '83% off', '82% off', '83% off', '71% off', '88% off', '66% off', '86% off', '69% off', '88% off', '76% off', '85% off']
----------------------------

In [81]:
## For next third page getting url:-
driver.get("https://www.flipkart.com/search?q=sun+glasses&sid=26x&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_12_na_na_na&as-pos=1&as-type=RECENT&suggestionId=sun+glasses%7CSunglasses&requestId=1542941d-3976-48a3-a353-2330fb313880&as-searchtext=Sun+Glasees+&page=3")

In [83]:
## Scrapping  Sunglasses Next 40 Brand name, Product Description,Price,Discount:-
Brand_100_list =[] 
product_desc_100 =[]
price_100_list =[]
discount_100_list =[]

## scrapping 3rd page brand name data
brand_100 = driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for i in brand_100:
    Brand_100_list.append(i.text)
print("-------------Brand Name--------------")    
print(Brand_100_list[:20]) 
print("---------------------------------------")

product_des_100 = driver.find_elements_by_xpath("//a[@class = 'IRpwTa']")
for i in product_des_100:
    product_desc_100.append(i.text)
print("-------------Product Description--------------")    
print(product_desc_100[:20]) 
print("---------------------------------------")

#### Scrapping Price Data:-
pp_100 = driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for i in pp_100:
    price_100_list.append(i.text)
print("----------Price-------------")    
print(price_100_list[:20])    
print("----------------------------")

## SCRAPPING discount data
disc_100 = driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span")
for i in disc_100:
    discount_100_list.append(i.text)
print("----------Discount-------------")    
    
print(discount_100_list[:20])  

print("----------------------------")

-------------Brand Name--------------
['NuVew', 'kingsunglasses', 'ROYAL SON', 'Dannilo', 'NuVew', 'Singco India', 'Singco', 'hipe', 'Elligator', 'PHENOMENAL', 'ROYAL SON', 'Singco India', 'Fastrack', 'ROZZETTA CRAFT', 'Elligator', 'Singco', 'DEIXELS', 'Fastrack', 'New Specs', 'Singco India']
---------------------------------------
-------------Product Description--------------
['UV Protection, Night Vision, Riding Glasses Sports Sung...', 'UV Protection Rectangular Sunglasses (55)', 'UV Protection Retro Square Sunglasses (58)', 'Others Round Sunglasses (Free Size)', 'UV Protection, Mirrored Wayfarer Sunglasses (57)', 'Riding Glasses, UV Protection, Others Aviator Sunglasse...', 'UV Protection, Others Aviator Sunglasses (32)', 'Mirrored, UV Protection, Gradient Round Sunglasses (55)', 'UV Protection, Gradient Aviator Sunglasses (53)', 'UV Protection, Mirrored Retro Square Sunglasses (53)', 'UV Protection Round Sunglasses (50)', 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...', 'UV Protection Aviator Sunglasses (Free Size)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection Round Sunglasses (54)', 'UV Protection Aviator Sunglasses (Free Size)', 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...', 'Polarized Retro Square Sunglasses (Free Size)', 'UV Protection Rectangular Sunglasses (Free Size)', 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...']
---------------------------------------
----------Price-------------
['₹240', '₹259', '₹449', '₹188', '₹188', '₹201', '₹289', '₹189', '₹263', '₹299', '₹359', '₹664', '₹719', '₹396', '₹275', '₹189', '₹236', '₹639', '₹188', '₹203']
----------------------------
----------Discount-------------
['69% off', '82% off', '70% off', '81% off', '82% off', '86% off', '85% off', '87% off', '82% off', '85% off', '76% off', '77% off', '20% off', '82% off', '78% off', '81% off', '60% off', '20% off', '87% off', '70% off']
----------------------------

In [105]:
### Finally Making Flipcart 100 Sunglasses Brand Name,Product description,Price,Discount data's  dataframe:-
Final_Brand_Name = []
Final_Brand_Name = Brand_100_list[:20] + BrandNext + Brand
print( Final_Brand_Name)

print("---------------------------------------------------")
Final_Product_desc =[]
Final_Product_desc = product_desc_100[:20] + product_desc_next +product_desc
print(Final_Product_desc)
print("---------------------------------------------------")
Final_Price =[]
Final_Price = price_100_list[:20] +price_next+ price
print(Final_Price)
print("------------------------------------------------------")
Final_Discount =[]
Final_Discount = discount_100_list[:20]+discount_next+ discount
print(Final_Discount)

Sunglasses_df = pd.DataFrame({'Brand Name':Final_Brand_Name,
                  'Description':Final_Product_desc,
                  'Price' :Final_Price,
                  'Discount':Final_Discount
    
                  })

Sunglasses_df

['NuVew', 'kingsunglasses', 'ROYAL SON', 'Dannilo', 'NuVew', 'Singco India', 'Singco', 'hipe', 'Elligator', 'PHENOMENAL', 'ROYAL SON', 'Singco India', 'Fastrack', 'ROZZETTA CRAFT', 'Elligator', 'Singco', 'DEIXELS', 'Fastrack', 'New Specs', 'Singco India', 'Fastrack', 'kingsunglasses', 'PIRASO', 'Dannilo', 'Fastrack', 'SRPM', 'hipe', 'Singco India', 'PIRASO', 'Johaena', 'Fastrack', 'Singco', 'AISLIN', 'GANSTA', 'hipe', 'Singco India', 'Lee Topper', 'kingsunglasses', 'PIRASO', 'ROZZETTA CRAFT', 'New Specs', 'agera', 'ROZZETTA CRAFT', 'VILLAIN', 'kingsunglasses', 'GANSTA', 'ROZZETTA CRAFT', 'Dannilo', 'Fastrack', 'DEIXELS', 'kingsunglasses', 'ZOSTAL', 'Lee Topper', 'Elligator', 'ROYAL SON', 'Singco India', 'Rich Club', 'PIRASO', 'ROYAL SON', 'Fravy', 'NuVew', 'kingsunglasses', 'ROYAL SON', 'Dannilo', 'NuVew', 'Singco India', 'Singco', 'hipe', 'Elligator', 'PHENOMENAL', 'ROYAL SON', 'Singco India', 'Fastrack', 'ROZZETTA CRAFT', 'Elligator', 'Singco', 'DEIXELS', 'Fastrack', 'New Specs', 'Singco India', 'ROYAL SON', 'ROZZETTA CRAFT', 'Silver Kartz', 'ROZZETTA CRAFT', 'kingsunglasses', 'Rich Club', 'Elligator', 'VILLAIN', 'AISLIN', 'AISLIN', 'PHENOMENAL', 'Dannilo', 'PHENOMENAL', 'Fastrack', 'kingsunglasses', 'hipe', 'ROYAL SON', 'SUNBEE', 'Elligator', 'ZOSTAL']
---------------------------------------------------
['UV Protection, Night Vision, Riding Glasses Sports Sung...', 'UV Protection Rectangular Sunglasses (55)', 'UV Protection Retro Square Sunglasses (58)', 'Others Round Sunglasses (Free Size)', 'UV Protection, Mirrored Wayfarer Sunglasses (57)', 'Riding Glasses, UV Protection, Others Aviator Sunglasse...', 'UV Protection, Others Aviator Sunglasses (32)', 'Mirrored, UV Protection, Gradient Round Sunglasses (55)', 'UV Protection, Gradient Aviator Sunglasses (53)', 'UV Protection, Mirrored Retro Square Sunglasses (53)', 'UV Protection Round Sunglasses (50)', 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...', 'UV Protection Aviator Sunglasses (Free Size)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection Round Sunglasses (54)', 'UV Protection Aviator Sunglasses (Free Size)', 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...', 'Polarized Retro Square Sunglasses (Free Size)', 'UV Protection Rectangular Sunglasses (Free Size)', 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...', 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)', 'Mirrored, UV Protection Aviator Sunglasses (56)', 'UV Protection Butterfly Sunglasses (65)', 'Others Round Sunglasses (Free Size)', 'UV Protection Sports Sunglasses (Free Size)', 'UV Protection Wayfarer Sunglasses (53)', 'Mirrored, UV Protection, Gradient Round Sunglasses (55)', 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...', 'UV Protection, Polarized Aviator Sunglasses (32)', 'Riding Glasses, UV Protection Oval Sunglasses (52)', 'UV Protection Wayfarer Sunglasses (Free Size)', 'UV Protection Aviator Sunglasses (Free Size)', 'UV Protection, Gradient Butterfly, Retro Square Sunglas...', 'UV Protection Aviator Sunglasses (57)', 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...', 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...', 'Riding Glasses, Night Vision Wrap-around Sunglasses (Fr...', 'UV Protection Round Sunglasses (Free Size)', 'UV Protection Aviator Sunglasses (54)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection Rectangular Sunglasses (Free Size)', 'Gradient Aviator Sunglasses (55)', 'UV Protection, Riding Glasses Rectangular Sunglasses (F...', 'Others Retro Square Sunglasses (Free Size)', 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)', 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)', 'UV Protection, Gradient Retro Square Sunglasses (Free S...', 'Gradient, Night Vision, Riding Glasses Round, Oval Sung...', 'UV Protection Wayfarer Sunglasses (55)', 'UV Protection Aviator, Wayfarer Sunglasses (Free Size)', 'UV Protection, Mirrored Round Sunglasses (54)', 'UV Protection Wrap-around Sunglasses (Free Size)', 'UV Protection, Riding Glasses Retro Square, Spectacle ...', 'UV Protection Round Sunglasses (55)', 'UV Protection, Gradient Butterfly Sunglasses (57)', 'Mirrored, UV Protection, Riding Glasses, Others Wrap-ar...', 'UV Protection, Others Round Sunglasses (48)', 'UV Protection Aviator Sunglasses (58)', 'Mirrored Aviator Sunglasses (58)', 'UV Protection, Gradient, Night Vision Retro Square Sung...', 'UV Protection, Night Vision, Riding Glasses Sports Sung...', 'UV Protection Rectangular Sunglasses (55)', 'UV Protection Retro Square Sunglasses (58)', 'Others Round Sunglasses (Free Size)', 'UV Protection, Mirrored Wayfarer Sunglasses (57)', 'Riding Glasses, UV Protection, Others Aviator Sunglasse...', 'UV Protection, Others Aviator Sunglasses (32)', 'Mirrored, UV Protection, Gradient Round Sunglasses (55)', 'UV Protection, Gradient Aviator Sunglasses (53)', 'UV Protection, Mirrored Retro Square Sunglasses (53)', 'UV Protection Round Sunglasses (50)', 'Gradient, Toughened Glass Lens, UV Protection Retro Squ...', 'UV Protection Aviator Sunglasses (Free Size)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection Round Sunglasses (54)', 'UV Protection Aviator Sunglasses (Free Size)', 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...', 'Polarized Retro Square Sunglasses (Free Size)', 'UV Protection Rectangular Sunglasses (Free Size)', 'UV Protection, Riding Glasses, Others Aviator, Wayfarer...', 'UV Protection Retro Square Sunglasses (58)', 'UV Protection Retro Square Sunglasses (Free Size)', 'UV Protection Aviator Sunglasses (88)', 'UV Protection, Gradient Rectangular Sunglasses (Free Si...', 'UV Protection, Mirrored Round Sunglasses (Free Size)', 'UV Protection Round Sunglasses (50)', 'UV Protection, Riding Glasses Rectangular, Retro Square...', 'Others Retro Square Sunglasses (Free Size)', 'UV Protection, Gradient Butterfly, Retro Square Sunglas...', 'Toughened Glass Lens, UV Protection Aviator Sunglasses ...', 'UV Protection, Mirrored Retro Square Sunglasses (Free S...', 'Gradient, Night Vision, Riding Glasses Round, Oval Sung...', 'UV Protection Retro Square Sunglasses (Free Size)', 'UV Protection Wrap-around Sunglasses (Free Size)', 'UV Protection, Night Vision Wayfarer Sunglasses (Free S...', 'UV Protection, Gradient, Mirrored, Riding Glasses Aviat...', 'Polarized Rectangular Sunglasses (65)', 'UV Protection, Polarized Wayfarer Sunglasses (Free Size...', 'Mirrored Round Sunglasses (53)', 'UV Protection Wrap-around Sunglasses (Free Size)']
---------------------------------------------------
['₹240', '₹259', '₹449', '₹188', '₹188', '₹201', '₹289', '₹189', '₹263', '₹299', '₹359', '₹664', '₹719', '₹396', '₹275', '₹189', '₹236', '₹639', '₹188', '₹203', '₹639', '₹211', '₹336', '₹188', '₹719', '₹220', '₹189', '₹664', '₹164', '₹156', '₹719', '₹189', '₹401', '₹269', '₹209', '₹203', '₹276', '₹279', '₹187', '₹383', '₹169', '₹196', '₹426', '₹549', '₹259', '₹209', '₹349', '₹244', '₹579', '₹202', '₹211', '₹168', '₹375', '₹239', '₹664', '₹279', '₹245', '₹299', '₹359', '₹285', '₹240', '₹259', '₹449', '₹188', '₹188', '₹201', '₹289', '₹189', '₹263', '₹299', '₹359', '₹664', '₹719', '₹396', '₹275', '₹189', '₹236', '₹639', '₹188', '₹203', '₹449', '₹325', '₹255', '₹383', '₹249', '₹383', '₹318', '₹549', '₹446', '₹691', '₹319', '₹244', '₹319', '₹719', '₹279', '₹209', '₹664', '₹276', '₹263', '₹168']
------------------------------------------------------
['69% off', '82% off', '70% off', '81% off', '82% off', '86% off', '85% off', '87% off', '82% off', '85% off', '76% off', '77% off', '20% off', '82% off', '78% off', '81% off', '60% off', '20% off', '87% off', '70% off', '20% off', '83% off', '87% off', '81% off', '20% off', '77% off', '87% off', '77% off', '89% off', '87% off', '20% off', '81% off', '73% off', '86% off', '79% off', '70% off', '88% off', '82% off', '88% off', '80% off', '89% off', '82% off', '80% off', '26% off', '87% off', '88% off', '82% off', '83% off', '27% off', '83% off', '82% off', '83% off', '71% off', '88% off', '66% off', '86% off', '69% off', '88% off', '76% off', '85% off', '69% off', '82% off', '70% off', '81% off', '82% off', '86% off', '85% off', '87% off', '82% off', '85% off', '76% off', '77% off', '20% off', '82% off', '78% off', '81% off', '60% off', '20% off', '87% off', '70% off', '70% off', '80% off', '78% off', '80% off', '85% off', '61% off', '78% off', '26% off', '70% off', '81% off', '84% off', '83% off', '84% off', '20% off', '83% off', '79% off', '66% off', '78% off', '89% off', '83% off']

,Brand Name,Description,Price,Discount
0,NuVew,"UV Protection, Night Vision, Riding Glasses Sp...",₹240,69% off
1,kingsunglasses,UV Protection Rectangular Sunglasses (55),₹259,82% off
2,ROYAL SON,UV Protection Retro Square Sunglasses (58),₹449,70% off
3,Dannilo,Others Round Sunglasses (Free Size),₹188,81% off
4,NuVew,"UV Protection, Mirrored Wayfarer Sunglasses (57)",₹188,82% off
...,...,...,...,...
95,hipe,"UV Protection, Gradient, Mirrored, Riding Glas...",₹209,79% off
96,ROYAL SON,Polarized Rectangular Sunglasses (65),₹664,66% off
97,SUNBEE,"UV Protection, Polarized Wayfarer Sunglasses (...",₹276,78% off
98,Elligator,Mirrored Round Sunglasses (53),₹263,89% off
99,ZOSTAL,UV Protection Wrap-around Sunglasses (Free Size),₹168,83% off

In [40]:
driver.close()

# 4.Scrapping IPhone11 first 100 Review from Flipcart webpage

In [110]:
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [114]:
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART")

In [118]:
### Scrapping Rating,Review Summary,Full review:-

### Making empty lists
rating_1 =[]
short_review1 = []
full_review1 =[]

## Scrapping Rating on 1st page
rating_data = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data:
    rating_1.append(i.text)
print("--------------------------")    
print(rating_1)
print("-----------------------------")

## Scrapping Short review on 1st page

sr = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr:
    short_review1.append(i.text)
    
print("--------------------------")    
print(short_review1)
print("-----------------------------")

## Scrapping Full review on 1st page


fr = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr:
    full_review1.append(i.text)
    
print(full_review1)

--------------------------
['5', '5', '5', '5', '5', '5', '5', '4', '5', '5']
-----------------------------
--------------------------
['Brilliant', 'Simply awesome', 'Best in the market!', 'Perfect product!', 'Worth every penny', 'Fabulous!', 'Great product', 'Good choice', 'Worth every penny', 'Highly recommended']
-----------------------------
['The Best Phone for the Money\n\nThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.\n\nCompelling ultra-wide camera\nNew Night mode is excellent\nLong battery life', 'Really satisfied with the Product I received... It’s totally genuine and the packaging was also really good so if ur planning to buy just go for it.', 'Great iPhone very snappy experience as apple kind. Upgraded from iPhone 7.\nPros\n-Camera top class\n- Battery top performed\n-Chipset no need to say as apple kind\n-Security as you expect from apple\n- Display super bright industry leading colour\naccuracy and super responsive\n-Build quality as expect from apple sturdy\npremium durable beautiful stylish.\n-Os most stable os in smartphone industry\n\nCons\n-No 5G\n-Display is not based on OLED technology\n-Charger headphones and 1 apple stic...\nREAD MORE', 'Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .', 'Previously I was using one plus 3t it was a great phone\nAnd then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11\nI have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display\nBut I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red\nMy experience after using 3 weeks\n1. The delivery ...\nREAD MORE', 'This is my first iOS phone. I am very happy with this product. Very much satisfied with this. I love this phone.', 'Amazing Powerful and Durable Gadget.\n\nI’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.\n\nI shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.\n\nDon’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.\n\nI’ve attached my puppy pics and no fi...\nREAD MORE', 'So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome', 'i11 is worthy to buy, too much happy with the product. Thank u flipkart I received the item on time..loved it..', 'iphone 11 is a very good phone to buy only if you can compromise for the display. The display on this is device is pretty good but you can get other options with better displays in this price segment.\nIf you can survive with an HD+ LCD panel with thicker bezels and a notch up top then this is a very good phone for you.\nCameras are awesome, battery backup excellent, great performance and a decent premium look. Good job Apple !']

In [119]:
## Scrapping on 2nd page:

## taking driver to the url:
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=2")

In [120]:
### Making empty lists
rating_2 =[]
short_review2 = []
full_review2 =[]

## Scrapping Rating on 2nd page
rating_data2 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data2:
    rating_2.append(i.text)
print("--------------------------")    
print(rating_2)
print("-----------------------------")

## Scrapping Short review on 2nd page

sr2 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr2:
    short_review2.append(i.text)
    
print("--------------------------")    
print(short_review2)
print("-----------------------------")

## Scrapping Full review on 2nd page


fr2 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr2:
    full_review2.append(i.text)
    
print(full_review2)

--------------------------
['5', '5', '5', '5', '5', '5', '5', '5', '5', '5']
-----------------------------
--------------------------
['Highly recommended', 'Perfect product!', 'Perfect product!', 'Classy product', 'Perfect product!', 'Worth every penny', 'Highly recommended', 'Simply awesome', 'Worth every penny', 'Worth every penny']
-----------------------------
['What a camera .....just awesome ..you can feel this iPhone just awesome . Good for gaming also ...try pubg in hd it’s just wow', 'It’s a must buy who is looking for an upgrade from previous generation of iPhones. If you are using XR then still you can hold on for sometime and upgrade to 2020 model else this phone is a must buy . Camera quality is amazing and wide angle is something to count upon. Performance wise it’s amazing and feels premium while holding in hand. So a big YES for this device. Go for 128 GB variant as the 4K videos will occupy lots of space and the storage can get over very quickly. Try to buy it with...\nREAD MORE', 'Value for money❤️❤️\nIts awesome mobile phone in the world ...\nDisplay was very good and bright ..\nTrust me freinds you r never regret after Buying..\nJust go for it....\nI love this phone and i switch to iphone x to 11', 'Totally in love with this ❤ the camera quality is amazing just love it 😘😘😘 itsss dammnnnnnn amazing... Must buy iPhone 11 this is my best experience ever ☀👌👌🧡🧡🧡🧡🧡 thanku apple ❤', "Iphone is just awesome.. battery backup is very very nice.. continuously for 10 hours we can use it.camera is just awesome.. display is just fab.i love it alot..i had to wait 15 days for it as i pre ordered it..overalll it's worth the price..these all images are clicked by my iPhone..and i love it.", 'Best budget Iphone till date ❤️ go for it guys without second thought. Let me explain you guys about Camera, Display, battery, and performance.\n\nCamera: at this price range there is no comparison of camera, you’ll love the picture quality as well as video quality. I am a Vlogger I wanted an iPhone with 4k video by front camera and I got this phone and I am more than happy 😃\n\nBattery: I use this phone roughly as I am active social media person and I have a youtube channel. so the battery ba...\nREAD MORE', "It's my first time to use iOS phone and I am loving my upgradation 😍😍 I love the color, I love the assebility of the phone....I need to learn more about its functionality, but as far as I have seen, it's quite easy and it has a lot of functions to work on, specially if you are a content writer or a blogger you get a lot of content creation platforms and they are really amazing.\n\nThis phone not only for good quality photography but a lot of other task too.😍💯", 'Excellent camera, good performance, no lag. The lcd display is also good.. but difference come when we watch movie in prime and Netflix, the colours are not vibrant.. as we see in amoled display.. and the charger in box is of 5 watts.. takes more than 3 hours to charge from 0 to 100.. so guys be prepare to buy 18 watts charger . Finally I am an android user, it was my first Iapple phone, I promise u guys the iOS is so smooth.. overall the phone is damn good.... close eyes to buy it.. thanks t...\nREAD MORE', 'It’s been almost a month since I have been using this phone. I upgraded from an iPhone 8. The main issue with my 8 was battery and this phone is just awesome when it comes to battery. It lasts a day and a half for me with my regular use , internet connected always with 4g\nCan’t move forward without saying this. Battery of this phone is a life saver when I am traveling or at work when I don’t get the option to charge\nCamera is superb. Front cam selfies and back cam photos are just awesome.\n...\nREAD MORE', 'Smooth like butter, camera like fantabulous, sound is crystal clear & its red color is damn attractive, i am just loving it. Must buy if you love photography.\n\nLucky to get it in sale, thank you Flipkart.']

In [121]:
## Scrapping on 3rd page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=3")

In [122]:
### Making empty lists
rating_3 =[]
short_review3 = []
full_review3 =[]

## Scrapping Rating on 3rd page
rating_data3 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data3:
    rating_3.append(i.text)
print("--------------------------")    
print(rating_3)
print("-----------------------------")

## Scrapping Short review on 3rd page

sr3 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr3:
    short_review3.append(i.text)
    
print("--------------------------")    
print(short_review3)
print("-----------------------------")

## Scrapping Full review on 3rd page


fr3 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr3:
    full_review3.append(i.text)
    
print(full_review3)

--------------------------
['5', '5', '4', '5', '5', '5', '5', '4', '5', '5']
-----------------------------
--------------------------
['Terrific', 'Wonderful', 'Nice product', 'Perfect product!', 'Brilliant', 'Classy product', 'Must buy!', 'Good choice', 'Perfect product!', 'Wonderful']
-----------------------------
['Really worth of money. i just love it. It is the best phone ever.', 'This is my first ever I phone. Before this I was using my google nexus 5. But moving from android to iOS is a great experience. It’s worth at this price. I will highly recommend it if you want to move to iOS. The best part of this phone is it’s camera and it’s battery life. This two things have won my heart. I loved it. Happy to have it in my hand. Still exploring its features. And can’t forget to mention Flipkart service. Very prompt service and fast delivery.', 'Awesome Phone. Slightly high price but worth. Better than iPhone XR.\nCamera is superb and wide angle camera is very clear.\n12MP selfie camera is also very good.\nA13 Chip gives a very good and smooth performance.', 'Battery backup is extraordinary, camera is decent & performance offered by A13 bionic is awsome. The display is good in practical usage like the visibility of display is very good in direct sun light compare to pro models. Iam extremely satisfied for the money I spent.', 'I have migrated from OP 7pro... and trust me, iPhone 11 is totally worth it.. following are the reasons:-\n1)there is ABSOLUTELY NO ISSUE WITH THE DISPLAY... its crisp, sharp and I found it to be much much better than OP7 pro. Netflix, Prime video all run crisply... you won’t miss a thing. True Tone works flawlessly...the display brightness is perfect. OP have not calibrated their screens properly.\n2) iPhone 11 series have really good cameras... others have spoken in depth about them.\n3) bat...\nREAD MORE', 'Superb Product !!!\nA big and worthy upgrade from mi 3S to iphone 11 .\nTotally loved it !', 'It’s an amazing product from apple and the camera is simply superb. Phone is faster.Night shot is simply superb and detailing and colour differentiation from camera is an added advantage\n\nThis review I have written from iPhone 11 only and I am glad to say outside.\n\nCons wise if we see HD+ display only, no battery percentage indicator as in older iPhone 8.\nNo assistive touch control button in it\nNo oleophobic coating on back panel glass and finger prints are visible but since I bought mint gr...\nREAD MORE', 'Looking so good 👍 😍 super 👌 stylish 😎 phone\nClean box 📦 good 👍 delivery 👌 fast delivery\nOriginal box Original iphone 📱 👌 😍😍😍', 'After 1 month use I found camera quality best compared to my previous Samsung note 10+.Display not good as note 10 also charging too slow.Apple should add fast charger like 11 plus and pro.Best phone for daily use', 'I just directly switch from iphone 6s to iphone 11 .The best premium smartphone I recommend to everyone. Excellent quality and colors the iphone have in 11 series.\nCamera quality is just awesome and the major feel when we hold in our hands. The sound quality and volume is also higher then the previous models.\nI will recommend to buy iphone 11 instead of pro models , there is nothing much difference as this model contains everything which fulfill our needs.\n\nOnly one thing that I dislike abo...\nREAD MORE']

In [123]:
## Scrapping on 4th page:

## taking driver to the url:
driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=4")

In [124]:
### Making empty lists
rating_4 =[]
short_review4 = []
full_review4=[]

## Scrapping Rating on 4th page
rating_data4 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data4:
    rating_4.append(i.text)
print("--------------------------")    
print(rating_4)
print("-----------------------------")

## Scrapping Short review on 4th page

sr4 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr4:
    short_review4.append(i.text)
    
print("--------------------------")    
print(short_review4)
print("-----------------------------")

## Scrapping Full review on 4th page


fr4 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr4:
    full_review4.append(i.text)
    
print(full_review4)

--------------------------
['5', '5', '5', '5', '5', '5', '5', '4', '5']
-----------------------------
--------------------------
['Terrific purchase', 'Simply awesome', 'Great product', 'Terrific purchase', 'Mind-blowing purchase', 'Excellent', 'Simply awesome', 'Good quality product', 'Very poor', 'Classy product']
-----------------------------
['Upgraded from iphone 6 to 11 best phone for iphone users battery is much better than other iphones camera is awesome love to use it.camera is so clear in night.', "It's very high performances devise i am like the service of flipkart delevary very fast and packing very nice perfect phone", 'Well you all know the specifications . One of a kind. Best iPhone till date. Many enhancements to the camera app with many options. Love the glass body with matte finish in the lens area on the back. Lovely colours to choose from. Best battery in an iPhone till date, enough to last more than a day in normal usage. I tested my iPhone 11 battery and lasted for than 24 hours after full charge still with 30% battery charge left. Watched movies for some time. Normal usage on calls, browsing, musi...\nREAD MORE', 'The built quality is not very premium.\nThe battery back is great .\nThe LCD panel is not so sharp but the brightness level is very High .\nCamera is super duper awesome.\nThe red colour which people think is bright is actually very soothing and excellent colour to choose from .\nThe A13 Bionic chip is really a flagship processor and can beat any phone which even has 12 gb ram .\nCamera module is very great and looks very stylish.', 'This will help you more. See if you are planning to buy iPhone 11. I will say. Yes. But there are some plans I just want to disclose before you buy. 1) If you are an existing iPhone X/XS/XS Max/ XR user, better you guys do not think it to buy. You guys have more or less better gadget. 2) If you are an android user and planning to buy premium phone. I will suggest them to please buy iPhone instead of buying an Android. I bet you will never go back to android after using IOS. Now I want to shar...\nREAD MORE', 'Amazing camera and feel super machine I am not describe my feeling but this is amazing Phone I am so lucky I have this', 'Really good actually this is my first apple product am using its really awesome performance wise excellent. Am really happy with this iphone11', 'it is very good at performance. Camera is best like before and very smooth response even in water. Don’t buy 12 mini buy iPhone 11 , it is far better than 12 mini believe me ! Have a nice day \uf8ff ☺️', 'Reviewing again after 5 months. At the beginning the battery and performance was good but it degraded soon. Also I was facing heating issues. The mobile will heat up like a stove sometimes. You cannot even play Pubg even in low settings properly, performance is not a problem but heating is. Also if you play that game for 10 mins the brightness will be automatically down due to over heating even when the auto brightness is set to off. This will not be solved even if u manually increase the bri...\nREAD MORE', 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE']

In [125]:
## Scrapping on 5th page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=5")

In [126]:
### Making empty lists
rating_5 =[]
short_review5 = []
full_review5=[]

## Scrapping Rating on 5th page
rating_data5 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data5:
    rating_5.append(i.text)
print("--------------------------")    
print(rating_5)
print("-----------------------------")

## Scrapping Short review on 5th page

sr5 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr5:
    short_review5.append(i.text)
    
print("--------------------------")    
print(short_review5)
print("-----------------------------")

## Scrapping Full review on 5th page


fr5 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr5:
    full_review5.append(i.text)
    
print(full_review5)

--------------------------
['5', '5', '5', '5', '5', '5', '5', '4', '5', '5']
-----------------------------
--------------------------
['Must buy!', 'Fabulous!', 'Mind-blowing purchase', 'Mind-blowing purchase', 'Wonderful', 'Must buy!', 'Great product', 'Very Good', 'Classy product', 'Perfect product!']
-----------------------------
['Best Apple iPhone that i have bought at a very reasonable price, camera quality is next level just awesome n of superior quality android phones not even close(RIP) to that and also battery is really good but packaging by Flipkart of iPhone was very poor of such a expensive product, firstly im bit worried about the quality of product if i purchased it through online how was the product but i think now this was mine best decision to bought it through Flipkart online because i got genuine Apple...\nREAD MORE', "I can say I'm damn impressed with iPhone 11. As they says iPhone 11 have the toughest glass ever in the smartphone which you'll find on the front and back and it's totally smooth. The fit and finish is full apple quality - there's no sense that any cheaping out has happened in the construction. Without saying it's camera features this review won't complete. The iPhone 11 has a dual camera system, consisting of a wide angle len's that's pretty much same as found on the iPhone XR last year, but...\nREAD MORE", 'Best Quality Product OF iPhone Series , Sound Quality & Camera quality is very awesome, Battery Life is very Sufficient for 24 hr Backup With Full Internet Access , I love this this Product too much , It is very fast & making me Very fast in all my daily Routine\nHighlights;\n1.Camera: 5 STAR\n2.Video Recording: 5 star\n3.Night mODE sHOOTING & Camera:4 star\n4. Audio Quality: Awesome\n5. Battery : 5 Star\n6. Touch:5 Star\n7. Processor: Very Fast\nThe M...\nREAD MORE', 'First thanks to Flipkart for this amazing deal and phone is outstanding. I upgraded from iPhone 7 and this is like very big upgrade. But the packaging was very basic I expected a good packaging as they only wrapped one layer of bubble wrap which I don’t think is enough to protect this expensive phone. And I recommend this phone and seller as well.\n\nAnd I’m posting this review after using it for 4 days.', 'Superfast delivery by Flipkart. Thanks.\n\n1. iPhone 11 is a pretty solid phone for the money you are paying.\n2. All the bad reviews about the display is confusing. It’s not that bad.\n3. I switched from a Oneplus 7t. I have no complaints about the display quality of iPhone. Yes, it’s not OLED, so, we are missing on the deep blacks. But that’s it. It is a very colour accurate display. Gets adequately bright and I could not find any pixelation.\n4. Performance is one of the best, if not best, in ...\nREAD MORE', 'I rate this product 5* as it has got amazing user experience with the best performing A13 bionic processor. The screen responds and graphics rendering is top notch. With casual gaming and internet browsing, the battery lasts for approx. 1 day. Camera is very good. You will fall in love with the portrait mode. You can call me a loyal Apple customer or whatever but I won’t stop praising the products and overall experience. That user experience matters and is worth every penny you pay.\n\nBelow ar...\nREAD MORE', "Again back to apple iphone after a gap of 2-3 years. It's pleasure to use iOS and the quality product by Apple. Iphone 11 still works like a beast in 2021 also. It really capable of doing day to day usage as well as hard core gaming. Battery is awesome. I'm really too much satisfied with it. Apart fto the very gorgious IPS LCD (AMOLED will be better) everything is mind boggling. Iphone💕.", 'impressive super phone and best in class camera ,sound and face unlock is super fast just see and phone is unlock and fast in daily apps use', 'Well while switching from android to iOS the first thing you need to be careful about is that you will loose all your whatsapp chat backups as both are different operating systems. Camera clarity is awesome and though being an lcd screen clarity and resolution is good. Battery backup is also good unlike previous gen iPhone. So far the experience is good will Padre after a few months of usage.\n\nP.S the black is more of a dark grey shade and not jet black', 'In love with this iphone great performance,camera ,battery everything. Go for it have a uncompareble battery backup, no doubts in iPhone camera here You can see the picture which is shot on my iPhone In love with this iphone great performance,camera ,battery everything. Go for it have a uncompareble battery backup, no doubts in iPhone camera here You can see the picture which is shot on my iPhone In love with this iphone great performance,camera ,battery everything. Go for it have a uncompare...\nREAD MORE']

In [127]:
## Scrapping on 6th page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=6")

In [128]:
### Making empty lists
rating_6 =[]
short_review6 = []
full_review6=[]

## Scrapping Rating on 6th page
rating_data6 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data6:
    rating_6.append(i.text)
print("--------------------------")    
print(rating_6)
print("-----------------------------")

## Scrapping Short review on 6th page

sr6 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr6:
    short_review6.append(i.text)
    
print("--------------------------")    
print(short_review6)
print("-----------------------------")

## Scrapping Full review on 6th page


fr6 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr6:
    full_review6.append(i.text)
    
print(full_review6)

--------------------------
['5', '5', '4', '5', '5', '5', '5', '5', '5', '5']
-----------------------------
--------------------------
['Just wow!', 'Awesome', 'Pretty good', 'Terrific purchase', 'Awesome', 'Classy product', 'Brilliant', 'Terrific', 'Perfect product!', 'Awesome']
-----------------------------
['Best in class. Battery backup is good especially when you play games like Pubg COD. But it is sort of heavy when you hold in hands. Portrait mode is best to click pictures. Stage light effect is awesome. Try to click photos outside in nature because photos inside home or room will not give you the quality in any phone even in DSLR.', 'Very excited to have this phone. This phone has the real power unlike the android phones having SD 855 . The battery life is very good and the camera quality is excellent as comapred to redmi and other phones except google pixel. I M enjoying every single bit of it. Would recommed only if you have the budget.', 'I was using Iphone 6s and also Oneplus 6t. Both mobiles were perfectly alright in Photos, gaming, and smooth interface . My 6s mobile getting battery issue. thought upgrade to 11. Really like this mobile of its Internal storage (compare to 6s) , camera and its touch feeling. Its a worth buying mobile for me.', 'Its Very awesome product working and good camera quality and all about best product and also flipkart is very great deal and offer nice price', 'I am using this phone for 5 days and its one of the best camera out there ❤️ the screen is not oled and i am coming from iphone xs so its little bit not up to the mark i would say\nBut overall value for money💕😍the battery back up is far better than my iphone xs and its worth in my apple ecosystem💫❤️if u are an apple User and have the eco system then go for it❤️though i will be getting the new iphone but its pretty good💫', 'Best and amazing product.....phone looks so premium.... battary is also good as expected .... Wide angle camera is so addictive ...if you are a IOS lover....then this phone will be the best choice for you all!!💯🔥', 'Excellent camera and display touching very nice and smooth very improvement against iPhone XR and new processor is very fast', "I got this beast today. And I must say the picture quality of its camera is awesome. Both the cameras works fine.\n\nAs for as the processing is concerned, it runs without any lag. You can play and do whatever you want without a glitch.\n\nThe battery runs for a day with medium and high workload.\n\nThe display is good and the speakers are working fine.\n\nThe earphones doesn't have any base and you can use it for calling mostly.\n\nThe charging time is approximately for 90 minutes for full charging...\nREAD MORE", 'Awesome purchase. Amazing phone with good battery backup. It’s a top notch device. White colour looks amazing. Phone has a few extra feature than iPhone XR. Overall, this is value for money', 'Always love the apple products, upgraded from old iPhone 6S plus to this after having my first baby. I just love to click baby’s photos with it. Overall I just love this phone. Battery back up is okay, sound quality is good. Haven’t tested yet waterproof yet. Only one thing I hate is apple could have given charger & headphones in box.']

In [129]:
## Scrapping on 7th page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=7")

In [130]:
### Making empty lists
rating_7 =[]
short_review7 = []
full_review7=[]

## Scrapping Rating on 7th page
rating_data7 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data7:
    rating_7.append(i.text)
print("--------------------------")    
print(rating_7)
print("-----------------------------")

## Scrapping Short review on 7th page

sr7 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr7:
    short_review7.append(i.text)
    
print("--------------------------")    
print(short_review7)
print("-----------------------------")

## Scrapping Full review on 7th page


fr7 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr7:
    full_review7.append(i.text)
    
print(full_review7)

--------------------------
['5', '5', '5', '5', '4', '5', '5', '5', '4']
-----------------------------
--------------------------
['Perfect product!', 'Very poor', 'Fabulous!', 'Excellent', 'Must buy!', 'Value-for-money', 'Best in the market!', 'Brilliant', 'Terrific purchase', 'Good quality product']
-----------------------------
['Value for money\n5 star rating\nExcellent camera\nBattery backup full day in single charge.\n\nTougher and water resistant design, glossy back.\nThe screen has excellent brightness and contrast.\nApple A13 Bionic is the fastest smartphone chip on the planet.\nExcellent battery life, fast charging support.\nStereo speakers with great quality.', 'Please DONT buy from here,\n\nI purchased Apple iPhone 11. with an exchange of IPhone 7, the exchange did not go well, iPhone 7 had a small scratch out side screen which i could never identify till date, but the FLIPKART person could, so he reduced 50% from exchange rate. I decided not to trade in, but paid money.\n\niPhone 11 Detail Below\n---------------------------------------------\nIt came with no charging, then i have put for charging, it took lot of time for charging, the phone also showe...\nREAD MORE', 'awesome phone to have. it has got many smart features apart from mind blowing looks, camera, display, battery and sound. have fallen in love with this phone. must buy phone if you have got enough money. thanks to flipkart and apple of course..', 'Its a fabulous mobile look awesome performance unbeaten camera like dslr battery good i think this is a beast of mobile', 'Dear friends... I want to share my experience with you about this amazing I phone 11....this is my first iPhone and special things about this mobile is it has great camera, battery backup and awesome display.... I mean everything is perfect.loved it 👍👍👍', "Just got this iphone 11\nAnd it is most powerful mobile phone I have used ever\n\nSo,go for it if you want a phone with best specification like camera,battery backup,display, A13 bionic chip\n\nThat's my review about this phone but yours can be differ from me....", "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.", 'Amazing phone and on great deal I received with super fast delivery by Flipkart...', 'finally an iPhone with very nice battery backup. update from iPhone 7 and happy to have it. camera is not up to the mark in low light but overall a recommended phone if your budget allows 😀', "I'm switching this phone to oppo reno 10x zoom\nIt's really impressive\nRarely I'm missing smooth display touch response like oppo reno but\nI really loved it.\nCamera really impressive"]

In [131]:
## Scrapping on 8th page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=8")

In [132]:
rating_8 =[]
short_review8 = []
full_review8=[]

## Scrapping Rating on 8th page
rating_data8 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data8:
    rating_8.append(i.text)
print("--------------------------")    
print(rating_8)
print("-----------------------------")

## Scrapping Short review on 8th page

sr8 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr8:
    short_review8.append(i.text)
    
print("--------------------------")    
print(short_review8)
print("-----------------------------")

## Scrapping Full review on 8th page


fr8 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr8:
    full_review8.append(i.text)
    
print(full_review8)

--------------------------
['5', '5', '5', '4', '5', '5', '5', '5', '4']
-----------------------------
--------------------------
['Best in the market!', 'Perfect product!', 'Awesome', 'Value-for-money', 'Just wow!', 'Worthless', 'Super!', 'Perfect product!', 'Excellent', 'Nice product']
-----------------------------
['Damn this phone is a blast . Upgraded from android to ios and is a duperb experience. Battery backup is top notch and display also pretty good', 'Worth the money’ starting first from its performance it beats out all phones , second the smoothness of camera is awesome, contrast ratio is much than expected. Price will not matter if u r a quality person, if not other phones are available with better discount', 'I dreamt about this day from a long time.... Getting an iPhone with my own money.... Super happy and worth spending every penny', "I'm Really happy with the product\nDelivery was fast as well\n..it was a gift for my sister and she loved it so much.", 'Great iphone.\nI am writing this review after 2 months of usage.\nCamera is excellent, especially the nightmode\nDisplay perfect\nBattery backup awesome\nSound quality very good\nOverall Apple gives you a perfect iphone in this range.\nReally in love with iPhone 11', "Phone is awesome no doubt. But Camera & Display is not great. Performance is mind blowing.\nBut the phone is heating too much when charging or when you regularly used. It's experience after using 1 week. It's heating extrem when I play PUBG for 30 minutes.\nGo for iPhone 11 pro or 12. Otherwise go for Android phone you will get much better phone in less price.", 'Did an upgrade from 6s plus to iphone 11.\nAo far the experience is well and good. Felt smoother than 6s plus. The camera quality is superb. Battery backup is descent. Not a heavy user, and gets power more than a day. Go for it if you need an alrounder iphone in a competitve price.', 'It is just awesome mobile for this price from Apple,\n\nAfter 10 days review\n\nBattery enough for 1 day even 24*7 Internet will be on and mostly internet usage\n\nCamera is just awesome cool , android 64 MP is equal to this just 12 MP\n\nA13 Bionic chip will give more high performance without hanging\n\nAudio stereo speakers will give Dolby atoms sound with crystal clear\n\nVideo recording is like cinematic shots of every sec can be a 4K 60fps. Just awesome this phone\niPhone 11 loved one', "It was amazing experience for me. Honestly i am using iPhone first time so I don't have that much past experience about that. But after using 7 days this mobile i want to give some honest feedback.\n1- Display 9 out of 10\n2- Camera 9.5 out of 10\n3- Battery 7 out of 10\n4- Performance 9.5 out of 10\n5- Features & Functions 10 out of 10\n6- Outer looks and colour 10 out of 10\nRest i think i will understand after using this for few months.\nI will highly recommend you guys if you have budget then you...\nREAD MORE", "If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated."]

In [133]:
## Scrapping on 9th page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=9")

In [134]:
### Making empty lists
rating_9 =[]
short_review9 = []
full_review9=[]

## Scrapping Rating on 9th page
rating_data9 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data9:
    rating_9.append(i.text)
print("--------------------------")    
print(rating_9)
print("-----------------------------")

## Scrapping Short review on 9th page

sr9 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr9:
    short_review9.append(i.text)
    
print("--------------------------")    
print(short_review9)
print("-----------------------------")

## Scrapping Full review on 9th page


fr9 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr9:
    full_review9.append(i.text)
    
print(full_review9)

--------------------------
['5', '5', '5', '5', '5', '5', '5', '5', '5', '5']
-----------------------------
--------------------------
['Mind-blowing purchase', 'Wonderful', 'Classy product', 'Terrific', 'Excellent', 'Mind-blowing purchase', 'Mind-blowing purchase', 'Highly recommended', 'Excellent', 'Worth every penny']
-----------------------------
['awesome Phone Smooth Touch Too good Sexyy looks one word Awesome', 'Super and marvellous phone look very cute and nice sound. I love this phone i think white is good colur.Excellent camer 5*😍😘♥️♥️', 'Gifted my man on his 30th birthday 🎂 He loves it.. Him happy so i am more than happy 😍😘❤️🥰', 'I bought iPhone 11 On March 2021, And I am Writing this review after using the phone for 4 Months. I would Say Everything is fine, Top Performance, Nice Camera as Anyone would Expect from any series of iPhone but when the Question comes to Battery it is complicated. The Battery is fully optimised and it comes 3110 mAh capacity but the problem is with the charger. Honestly Apple Removed charger from in Box items in the name of Environment and they are also forcing us to buy any 20W PD 3rd part...\nREAD MORE', "Just go for it.\nThis phone is really amazing. I ordered it for my wife and we click photos on this thing which are better than dslr. I own OnePlus 6t but it's camera sucks. iPhone is really amazing when it comes to camera. It's worth spending 50k on this. Cons- only display is lcd. While using u don't feel it but if u compare with other phone then u can see difference quite easily.\nChanging from Android to iphone is bit difficult coz most of things u don't know but I liked it. Some of the a...\nREAD MORE", 'Absolutely powerful gadget. Loved it’s look! Soo glassy and classy. I would definitely recommend this model of Apple. Only disappointed with the 5W charger, one should purchase an 18W adapter for fast charging. Though battery backup is great. Bought it in September 2020, reviewing after so long so I’m gonna put the genuine review here.✅', 'Excellent camera 📸 And Display touching very Nice And Smooth and very improvement against\nI phone 11 and new processor is very fast', 'Thanks Flipkart For this amazing deal! I had a dream of owning a iphone since i had known about.\nIm very happy with my purchase & it is totally worth it.\nAmazing experience all over !!\n\nAnyone who’s thinking of buying it in 2021, i would simply say go for it without any second thoughts ❤️', 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11', 'Undoubtedly Iphone 11 is the most successful model till now and its performance is extraordinary and the security features are very impressive, display is more vibrant sound quality Camera Quality 5*****, but Iphone should add accessories too and act like scrooge.']

In [135]:
## Scrapping on 10th page:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=10")

In [136]:
### Making empty lists
rating_10 =[]
short_review10 = []
full_review10=[]

## Scrapping Rating on 10th page
rating_data10 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data10:
    rating_10.append(i.text)
print("--------------------------")    
print(rating_10)
print("-----------------------------")

## Scrapping Short review on 10th page

sr10 = driver.find_elements_by_xpath("//p[@class='_2-N8zT']")
for i in sr10:
    short_review10.append(i.text)
    
print("--------------------------")    
print(short_review10)
print("-----------------------------")

## Scrapping Full review on 10th page


fr10 = driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div")
for i in fr10:
    full_review10.append(i.text)
    
print(full_review10)

--------------------------
['4', '5', '5', '5', '5', '5', '3', '5', '5', '3']
-----------------------------
--------------------------
['Pretty good', 'Fabulous!', 'Fabulous!', 'Just wow!', 'Terrific purchase', 'Awesome', 'Decent product', 'Brilliant', 'Awesome', 'Does the job']
-----------------------------
["I've used this phone for over a month now and here are my takeaways.\nI would like to first talk about the best things about this phone and then the cons of it.\n\nPros:\nThis phone is a performance beast. It handles large games and applications effortlessly and you won't find any stutters or lags while playing graphic intensive games like pubg, cod , mortal kombat and asphalt.\n\nThis phone has only 4gb ram and yet the ram management is amazing, it can keep 3 heavy games in memory without reload...\nREAD MORE", 'I purchased the iPhone 11 a month back. I must say Apple has impressed me yet again . I have been an Apple user for past 5 years . The phone is power packed with amazing features . What impressed me the most was the battery backup the phone offers . Battery can easily run upto 1.5 days in single charge with moderate to\nHeavy usage . If you’re looking for a value for money device , I don’t see any other phone in the price range which can match the iPhone 11 .\nOne thing I didn’t like was that ...\nREAD MORE', 'Everything is perfect pictures come out so clearly and at first I wasn’t sure when I got it then when I started to use it and get the hang of it it was amazing!! I can’t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face...\nREAD MORE', 'The ultimate performance\nCamera is superb\nThe battery backup also very good i never saw iphone gives this much of battery backup\nIf any one wana buy iphone 11 definitely i will recommend this mobile\nIt has the better battery and powerfull processer peak performance glorious camera and the display also 100% high quality lcd display if u had money for for 12 if u dont wana invest much money on that then go for iphone 11 it has maximum same specs only main difference between the 12 and 11 is...\nREAD MORE', 'I use a Note10+ and have been using both iOS and Android devices.\n\nCamera has really good features and portraits are super good, better than Samsung flagship. Overall camera setup can still be enhanced and hopeful for better upgrades on software in next release\n\nOperating system is quite a breeze and user experience of daily usage is very high as compared to Android. I moved to iOS very swiftly in 2 days for all my office work from Note10+\n\nBattery holds up quite well with 4 hrs of call and ...\nREAD MORE', 'The phone is completely good\nAs far as camera Apple is king of it\nAnd its a beast in performance\nAnd the battery is pretty good too', 'Everything u ll like it when u use this iPhone. Simple changes only not many to lower models but it’s nice to use. Little heavy compared to previous models like 7,8', 'A wort full value for money decision it’s . Simply go for it in 2021 its still a good decision . Awesome camera , Super smothered performance, Heck of build quality. And Most important it protects your privacy.', 'Can’t beat the software and hardware integration of apple.\nPerforms like a beast. Great quality camera\n6-7 hours screen on time which is good. Nothing much to complaint about the screen. Good connectivity speeds.\nGreat buy and Flipkart’s delivery top notch as usual', "phone is good but in display is 720p lcd in this price range we can get full hd OLED displays with higher refresh rate processor is very good camera is nice but looks kind of oldish in front of todays phone also there's no charging in box had to buy it seperately"]

In [140]:
### Finally making DataFrame for first 100 reviews for IPhone11 :-

rating_final =[]
short_review_final = []
full_review_final=[]

rating_final = rating_1 + rating_2 + rating_3 + rating_4 +rating_5 + rating_6 + rating_7 + rating_8 + rating_9 + rating_10
print(len(rating_1))
print(len(rating_2))
print(len(rating_3))
print(len(rating_4))
print(len(rating_5))
print(len(rating_6))
print(len(rating_7))
print(len(rating_8))
print(len(rating_9))
print(len(rating_10))









print(len(rating_final))

short_review_final = short_review1 + short_review2 + short_review3 + short_review4 +short_review5 +short_review6 +short_review7 + short_review8 + short_review9 +short_review10
print(len(short_review_final))

full_review_final = full_review1 + full_review2 + full_review3 + full_review4 + full_review5 + full_review6 +full_review7 +full_review8 +full_review9 +full_review10
print(len(full_review_final))

10
10
10
9
10
10
9
9
10
10
97
100
100

In [141]:
## since on some pages rating reviews are only 9, so to make it 100 we scrap on 11th page only for rating data
## Scrapping on 11th page only for rating:

## taking driver to the url:

driver.get("https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART&page=11")

In [143]:
rating_11 = []
rating_data11 = driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']")
for i in rating_data11:
    rating_11.append(i.text)
print("--------------------------")    
print(rating_11)
print("-----------------------------")

--------------------------
['5', '5', '5', '5', '5', '4', '5', '4', '5', '5']
-----------------------------

In [144]:
rating_final = rating_final + rating_11[:3]
print(len(rating_final))

100

In [145]:
review_df = pd.DataFrame({'Rating' :rating_final,
                          'Short Review':short_review_final,
                           'Full Review':full_review_final
                          })
review_df

,Rating,Short Review,Full Review
0,5,Brilliant,The Best Phone for the Money\n\nThe iPhone 11 ...
1,5,Simply awesome,Really satisfied with the Product I received.....
2,5,Best in the market!,Great iPhone very snappy experience as apple k...
3,5,Perfect product!,Amazing phone with great cameras and better ba...
4,5,Worth every penny,Previously I was using one plus 3t it was a gr...
...,...,...,...
95,5,Awesome,The phone is completely good\nAs far as camera...
96,3,Decent product,Everything u ll like it when u use this iPhone...
97,5,Brilliant,A wort full value for money decision it’s . Si...
98,5,Awesome,Can’t beat the software and hardware integrati...
99,5,Does the job,phone is good but in display is 720p lcd in th...

In [146]:
driver.close()

# 5.Scrapping Data for 100 sneakers from FlipCart

In [41]:
## Instatiating chrome driver
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [42]:
## Get the specific url to the driver
driver.get("https://www.flipkart.com/")
#driver.get("https://www.flipkart.com/search?q=sneakers&as=on&as-show=on&otracker=AS_Query_OrganicAutoSuggest_3_8_na_na_na&otracker1=AS_Query_OrganicAutoSuggest_3_8_na_na_na&as-pos=3&as-type=RECENT&suggestionId=sneakers&requestId=ebbc7e06-5812-42e6-9184-6aff76138559&as-searchtext=sneakers")

In [43]:
## Finding xpath for search product:-
search_product = driver.find_element_by_xpath("//input[@class='_3704LK']")
search_product.send_keys("Sneakers")

In [44]:
search_button = driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_button.click()

In [168]:
### Making empty lists for Brand,Product Description,Price and discounts :-
Brand1 =[]
prod_desc1=[]
price1 =[]
disc1=[]

## Scrapping  first 40 Brand Name on page1:-
br1 = driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for i in br1:
    Brand1.append(i.text)
print("-------------Brand Name---------------------- ")    
print(Brand1)    
print("--------------------------------------------")

## Scrapping  first 40 Product Description on page1:-

pd1 = driver.find_elements_by_xpath("//a[@class='IRpwTa']")
for i in pd1:
    prod_desc1.append(i.text)
print("---------------Product Description-----------")  
print(prod_desc1)

print("--------------------------------------------")

## Scrapping first 40 Price on page1 :-

pp1 = driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for i in pp1:
    price1.append(i.text)
    
print("---------------Product Description-----------")  
print(price1)
print("---------------------------------------------")

## Scrapping first 40 Discount on page1:-

dc1 = driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span")
for i in dc1:
    disc1.append(i.text)
print("----------------Discount---------------------")  
print(disc1)
print("---------------------------------------------")

-------------Brand Name----------------------
['Echor', 'Robbie jones', 'Chevit', 'RapidBox', 'BRUTON', 'Shoes Bank', 'Numenzo', 'PUMA', 'SCATCHITE', 'Chevit', 'ganpati traders', 'Numenzo', 'Chevit', 'Chevit', 'BIRDE', 'Robbie jones', 'Edoeviv', 'Numenzo', 'Magnolia', 'Robbie jones', 'RED TAPE', 'BIRDE', 'T-ROCK', 'HRX by Hrithik Roshan', 'Rzisbo', 'Clymb', 'Robbie jones', 'Robbie jones', 'FLYING MACHINE', 'URBANBOX', 'Zsyto', 'NIKE', 'PACIFIER', 'BRUTON', 'Robbie jones', 'WROGN', 'PUMA', 'Kraasa', 'Chevit', 'PUMA']
--------------------------------------------
---------------Product Description-----------
["Men's Canvas Low Top Sneakers Lace-up Classic Casual Sn...", 'Sneakers For Men', 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...', 'Modern Trendy Shoes Sneakers For Men', "White Sneaker For Men's/Boy's Sneakers For Men", 'White Sneaker For Men Sneakers For Men', 'Puma Smash v2 SL one8 Sneakers For Men', 'Sneakers Sneakers For Men', 'Unique & Perfect Collection Combo Pack of 02 Shoes for ...', 'Sneakers For Men', 'Combo Pack of 5 Casual Sneakers Sneakers For Men', 'Combo Pack of 4 Casual Sneakers With Sneakers For Men', 'Sports Running Shoes Sneakers For Men', 'Sneakers For Men', "Luxury Branded Fashionable Men's Casual Walking Partywe...", '411 Casual Sneakers For Men', 'Sneakers For Men', 'Casual Sneakers White Shoes For Men Sneakers For Men', 'Sneakers For Men', 'Combo Pack of 2 Casual Shoes Sneakers For Men', 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Court Vapor Lite Hard Court Sneakers For Men', 'Sneakers For Men', 'Modern & Trendy Collection Combo Pack of 02 Shoes for M...', 'Casual Sneakers Black Shoes For Men Sneakers For Men', 'Lazy Knit Slip On Sneakers For Men', 'Shark-41 Sneakers For Men', 'Combo Pack of 3 Casual Shoes (Sneakers Shoes) Sneakers ...', 'Shuffle Sneakers For Men']
--------------------------------------------
---------------Product Description-----------
['₹349', '₹499', '₹699', '₹680', '₹379', '₹331', '₹479', '₹2,399', '₹398', '₹599', '₹145', '₹479', '₹899', '₹665', '₹299', '₹499', '₹499', '₹499', '₹419', '₹499', '₹1,319', '₹472', '₹379', '₹3,099', '₹549', '₹649', '₹499', '₹499', '₹2,218', '₹220', '₹328', '₹6,685', '₹499', '₹527', '₹451', '₹1,199', '₹2,783', '₹499', '₹745', '₹2,999']
---------------------------------------------
----------------Discount---------------------
['76% off', '50% off', '56% off', '31% off', '70% off', '66% off', '63% off', '40% off', '60% off', '60% off', '70% off', '63% off', '63% off', '66% off', '40% off', '50% off', '37% off', '75% off', '58% off', '50% off', '70% off', '52% off', '62% off', '20% off', '45% off', '56% off', '50% off', '50% off', '38% off', '77% off', '74% off', '1% off', '57% off', '78% off', '54% off', '50% off', '7% off', '50% off', '50% off', '40% off']
---------------------------------------------

In [169]:
## taking the url to second page:-
driver.get("https://www.flipkart.com/search?q=sneakers&as=on&as-show=on&otracker=AS_Query_OrganicAutoSuggest_3_8_na_na_na&otracker1=AS_Query_OrganicAutoSuggest_3_8_na_na_na&as-pos=3&as-type=RECENT&suggestionId=sneakers&requestId=ebbc7e06-5812-42e6-9184-6aff76138559&as-searchtext=sneakers&page=2")

In [170]:
### Making empty lists for Brand,Product Description,Price and discounts :-
Brand2 =[]
prod_desc2=[]
price2 =[]
disc2=[]

## Scrapping  next 40 Brand Name on page2:-
br2 = driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for i in br2:
    Brand2.append(i.text)
print("-------------Brand Name---------------------- ")    
print(Brand2)    
print("--------------------------------------------")

## Scrapping  next 40 Product Description on page2:-

pd2 = driver.find_elements_by_xpath("//a[@class='IRpwTa']")
for i in pd2:
    prod_desc2.append(i.text)
print("---------------Product Description-----------")  
print(prod_desc2)
print("--------------------------------------------")

## Scrapping next 40 Price on page2 :-

pp2 = driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for i in pp2:
    price2.append(i.text)
    
print("---------------Product Description-----------")  
print(price2)
print("---------------------------------------------")

## Scrapping next 40 Discount on page2:-

dc2 = driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span")
for i in dc2:
    disc2.append(i.text)
print("----------------Discount---------------------")  
print(disc2)
print("---------------------------------------------")

-------------Brand Name----------------------
['Zorth', 'D-SNEAKERZ', 'Clymb', 'Robbie jones', 'Chevit', 'FEWROK', 'ESSENCE', 'PUMA', 'Trendmode', 'BRUTON', 'Chevit', 'Numenzo', 'RODDICK SHOES', 'ESSENCE', 'Robbie jones', 'Robbie jones', 'Absolute comfort', 'BIRDE', 'believe', 'Robbie jones', 'Numenzo', 'HOTSTYLE', 'Absolute comfort', 'HRX by Hrithik Roshan', 'Robbie jones', 'TR', 'LuvShus', 'Robbie jones', 'STRANGER BROTHERS', 'Zsyto', 'BIRDE', 'NIKE', 'Chevit', 'flipy', 'SPARX', 'Robbie jones', 'Clymb', 'Stefano Rads', 'RapidBox', 'WROGN']
--------------------------------------------
---------------Product Description-----------
["Casual , Partywear Sneakers Shoes For Men's And Boys Wh...", 'Mesh Sports/Walking Shoes/Outdoor Ultra Lightweight Run...', 'Sneakers For Men', 'Perfect & Affordable Combo Pack of 02 Pairs Sneakers Ou...', 'Puma Smash v2 SL one8 Sneakers For Men', 'Combo Pack Of 4 Casual Sneakers For Men', '516 Trendy Star Perfect Sneakers For Men', 'Sneakers For Men', 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Birde Trendy Casual Shoes Sneakers For Men', 'Sneakers for men(black_6) Sneakers For Men', 'Casual Sneakers White Shoes For Men Sneakers For Men', 'Numenzo Black Sneaker For Men Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Men Casual Shoe New Trend With Fashion Panda Desgined L...', 'Sneakers For Men', 'Sneakers For Men', 'Birde Trendy Casual Shoes Sneakers For Men', 'Court Vapor Lite Hard Court Sneakers For Men', 'Combo Pack of 02 Pair Casual Sneakers Outdoor Sports Sh...', 'CASUAL Sneakers For Men', 'Canvas Casual Partywear Outdoor Sneakers Shoes For Mens...', 'Casual Sneakers Shoes For Men Sneakers For Men', 'Sneakers For Men']
--------------------------------------------
---------------Product Description-----------
['₹513', '₹348', '₹259', '₹499', '₹599', '₹424', '₹499', '₹2,399', '₹249', '₹699', '₹299', '₹479', '₹499', '₹539', '₹499', '₹499', '₹199', '₹299', '₹499', '₹499', '₹499', '₹349', '₹240', '₹3,099', '₹499', '₹599', '₹442', '₹499', '₹459', '₹418', '₹299', '₹6,685', '₹495', '₹449', '₹679', '₹449', '₹649', '₹242', '₹640', '₹1,199']
---------------------------------------------
----------------Discount---------------------
['48% off', '47% off', '74% off', '50% off', '53% off', '57% off', '50% off', '40% off', '75% off', '82% off', '62% off', '63% off', '50% off', '46% off', '50% off', '50% off', '60% off', '40% off', '50% off', '50% off', '61% off', '65% off', '75% off', '20% off', '50% off', '70% off', '55% off', '50% off', '54% off', '58% off', '40% off', '1% off', '66% off', '71% off', '15% off', '55% off', '56% off', '65% off', '35% off', '50% off']
---------------------------------------------

In [171]:
## taking the url to Third page:-
driver.get("https://www.flipkart.com/search?q=sneakers&as=on&as-show=on&otracker=AS_Query_OrganicAutoSuggest_3_8_na_na_na&otracker1=AS_Query_OrganicAutoSuggest_3_8_na_na_na&as-pos=3&as-type=RECENT&suggestionId=sneakers&requestId=ebbc7e06-5812-42e6-9184-6aff76138559&as-searchtext=sneakers&page=3")

In [172]:
### Making empty lists for Brand,Product Description,Price and discounts :-
Brand3 =[]
prod_desc3=[]
price3 =[]
disc3=[]

## Scrapping  next 20 Brand Name on page3:-
br3 = driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
for i in br3:
    Brand3.append(i.text)
print("-------------Brand Name---------------------- ")    
print(Brand3[:20])    
print("--------------------------------------------")

## Scrapping  next 20 Product Description on page2:-

pd3 = driver.find_elements_by_xpath("//a[@class='IRpwTa']")
for i in pd3:
    prod_desc3.append(i.text)
print("---------------Product Description-----------")  
print(prod_desc3[:20])
print("--------------------------------------------")

## Scrapping next 20 Price on page2 :-

pp3 = driver.find_elements_by_xpath("//div[@class='_30jeq3']")
for i in pp3:
    price3.append(i.text)
    
print("---------------Product Description-----------")  
print(price3[:20])
print("---------------------------------------------")

## Scrapping next 20 Discount on page2:-

dc3 = driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']/span")
for i in dc3:
    disc3.append(i.text)
print("----------------Discount---------------------")  
print(disc3[:20])
print("---------------------------------------------")

-------------Brand Name----------------------
['India hub', 'Robbie jones', 'SPARX', 'Robbie jones', 'RED TAPE', 'RODDICK SHOES', 'Chevit', 'PUMA', 'BRUTON', 'URBANBOX', 'Bond Street By Red Tape', 'Numenzo', 'Echor', 'Kraasa', 'BIRDE', 'Robbie jones', 'Chevit', 'Chevit', 'BIRDE', 'Robbie jones']
--------------------------------------------
---------------Product Description-----------
['Casual Sneakers White Shoes For Men Sneakers For Men', 'SM-322 Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Fashion Outdoor Canvas Casual Light Weight Lace-up Even...', 'Lightweight & Stylish Pack of 02 Pair Shoes for Men Cas...', 'Puma Smash v2 SL one8 Sneakers For Men', 'Lattest Sneakers Shoe Sneakers For Men', 'Sneakers For Men', "Echor Men's Sneakers Fashion Lightweight Running Shoes ...", 'Casuals, Canvas, Partywear Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'Smart Casuals Canvas Shoes Combo pack of 2 Sneakers For...', 'Sneakers For Men', 'Combo Pack of 2 Casual Shoes Sneakers For Men', 'Casual Sneakers White Shoes For Men Sneakers For Men', 'Modern Trendy Shoes Combo pack of 4 Sneakers For Men', 'Casual Sneakers Green Shoes For Men And Boys Sneakers F...', 'casual for men (blue 06) Sneakers For Men']
--------------------------------------------
---------------Product Description-----------
['₹474', '₹840', '₹499', '₹1,319', '₹499', '₹501', '₹2,399', '₹299', '₹166', '₹1,049', '₹479', '₹499', '₹499', '₹598', '₹499', '₹399', '₹399', '₹525', '₹499', '₹898']
---------------------------------------------
----------------Discount---------------------
['52% off', '15% off', '50% off', '70% off', '50% off', '66% off', '40% off', '76% off', '66% off', '73% off', '63% off', '66% off', '50% off', '40% off', '50% off', '60% off', '50% off', '47% off', '50% off', '40% off']
---------------------------------------------

In [185]:
## Finally making Dataframe for 100 Sneakers:-
brand_100 = []
desc_100 = []
price_100 = []
disc_100 = []

## Adding to get 100 Sneaker's Brand Name from FlipCart: -

brand_100 = Brand1 + Brand2 + Brand3[:20]
print(len(brand_100))

## Adding to get 100 Sneaker's Product Description from FlipCart: -

desc_100 = prod_desc1 + prod_desc2 + prod_desc3[:35]
# print(len(prod_desc1))
# print(len(prod_desc2))
# print(len(prod_desc3))

### Since  length of product description on page1 is 35,on second page only 30 and again on page 3 ,it is 36,
##so make it 100,I have taken 35 data.

print(len(desc_100))

## Adding to get 100 Sneaker's price  from FlipCart: -
price_100 = price1 + price2 + price3[:20]
print(len(price_100))

## Adding to get 100 Sneaker's Discount data  from FlipCart: -
disc_100 = disc1 + disc2 + disc3[:20]
print(len(disc_100))

#### Making DataFrame

sneaker_df = pd.DataFrame({'Brand Name': brand_100,
                           'Product Description':desc_100,
                           'Price':price_100,
                           'Discount':disc_100
    
                          })

sneaker_df

100
100
100
100

,Brand Name,Product Description,Price,Discount
0,Echor,Men's Canvas Low Top Sneakers Lace-up Classic ...,₹349,76% off
1,Robbie jones,Sneakers For Men,₹499,50% off
2,Chevit,Super Stylish & Trendy Combo Pack of 02 Pairs ...,₹699,56% off
3,RapidBox,Modern Trendy Shoes Sneakers For Men,₹680,31% off
4,BRUTON,White Sneaker For Men's/Boy's Sneakers For Men,₹379,70% off
...,...,...,...,...
95,Robbie jones,SM-322 Sneakers For Men,₹399,60% off
96,Chevit,Court Vapor Lite Hard Court Sneakers For Men,₹399,50% off
97,Chevit,Sneakers For Men,₹525,47% off
98,BIRDE,"Casual , Partywear Sneakers Shoes For Men's An...",₹499,50% off
99,Robbie jones,Luxury Fashionable Breathable Casual Sneakers ...,₹898,40% off

In [45]:
### Closing the driver:-
driver.close()

# 6.Scrapping shoes data  using colour and price filter from Myntra

In [220]:
## Instatiating chrome driver
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [221]:
## Taking driver to the specific url:-
driver.get("https://www.myntra.com/shoes?f=Color%3ABlack_36454f&rf=Price%3A7195.0_14130.0_7195.0%20TO%2014130.0")

In [227]:
## Creating empty lists for Brand,Short Description,and Price.:-
brand1 = []
Short_desc1=[]
price1=[]

## Scrapping Brand on page 1:- 
br1 = driver.find_elements_by_xpath("//h3[@class='product-brand']")
for i in br1:
    brand1.append(i.text)
print("-------------Brand---------------------------")    
print(brand1) 
print(len(brand1))
print("--------------------------------------------------")

## Scrapping Short Description on page 1:- 

sd1 = driver.find_elements_by_xpath("//h4[@class='product-product']")
for i in sd1:
    Short_desc1.append(i.text)
    
print("------------------Short Description------------------")
print(Short_desc1)
print(len(Short_desc1))
print("--------------------------------------------")

## Scrapping Price Data on page1 :-

pp1 = driver.find_elements_by_xpath("//div[@class='product-price']/span")
for i in pp1:
    price1.append(i.text)
print("-----------Price-----------------")  
print(price1)
print(len(price1))
print("---------------------------------")

for i in price1:
    print(i[:])

-------------Brand---------------------------
['Nike', 'Puma', 'UNDER ARMOUR', 'Nike', 'Nike', 'Hush Puppies', 'Hush Puppies', 'Puma', 'ASICS', 'Skechers', 'Puma', 'ASICS', 'Nike', 'Bugatti', 'Skechers', 'Calvin Klein', 'Bugatti', 'ASICS', 'Hush Puppies', 'ASICS', 'Calvin Klein', 'Hush Puppies', 'Calvin Klein', 'Calvin Klein', 'Hush Puppies', 'Puma', 'Saint G', 'Tommy Hilfiger', 'Bugatti', 'Tommy Hilfiger', 'Saint G', 'Cole Haan', 'Cole Haan', 'Saint G', 'Hush Puppies', 'Saint G', 'MANGO', 'Saint G', 'DAVINCHI', 'Hush Puppies', 'J.FONTINI', 'Tommy Hilfiger', 'Pavers England', 'DAVINCHI', 'DAVINCHI', 'Saint G', 'Pavers England', 'Bugatti', 'Puma', 'Saint G']
50
--------------------------------------------------
------------------Short Description------------------
['Men Zoom Span 4 Running Shoes', 'Men Deviate Nitro Running Shoe', 'Men HOVR Apex 2 Training', 'Men Waffle One SE Sneakers', 'Men FLIGHT LEGACY Sneakers', 'Men Formal Derbys', 'Men Solid Leather Formal Derbys', 'Men Running Shoes', 'Men Running Shoes', 'Men Balance Anchor Walking', 'Men Electrify Nitro Running', 'Men GEL-KAYANO 27 Shoes', "Men BlazerLow '77 Sneakers", 'Men Running Shoes', 'Men Go Run Hyper Burst Running', 'Men Textured Leather Sneaker', 'Men Textured Leather High-Top Flat Boots', 'Men Colourblocked PU Sneakers', 'Men Solid Formal Slip-Ons', 'Skycourt Sneakers', 'Men UV MONO Leather Sneakers', 'Men Solid Leather Formal Slip-Ons', 'Men Solid Leather Sneakers', 'Men Solid Low Top LTH Sneakers', 'Men Solid Leather Formal Slip-Ons', 'Women Eternity NITRO Shoes', 'Leather Boots with Buckles', 'Men Lightweight Sneakers', 'Leather Block Heeled Boots', 'Women Leather Block Pumps', 'Women High-Top Heeled Boots', 'Men Wingtip Oxford Sneakers', 'Men GENERATION ZEROGRAND STITCHLITE', 'Women Leather Heeled Boots', 'Men Leather Slip-On Sneakers', 'Men Mid-Top Chelsea Boots', 'Textured High-Top Flat Boots', 'Men Leather Chelsea Boots', 'Men Textured Formal Loafers', 'Men Leather Derbys', 'Men Textured Leather Loafers', 'Women ELEVATED Leather Sneaker', 'Men Textured Leather Formal Derbys', 'Men Textured Formal Leather Loafers', 'Men Textured Formal Leather Loafers', 'Leather Block Heeled Boots', 'Men Solid Leather Formal Loafers', 'Leather Heeled Knee Boots', 'Men FUTURE 5.1 Football Shoes', 'Women Leather Heeled Boots']
50
--------------------------------------------
-----------Price-----------------
['Rs. 7195', 'Rs. 11249Rs. 14999', '(25% OFF)', 'Rs. 13999', 'Rs. 8295', 'Rs. 7595Rs. 7995', '(5% OFF)', 'Rs. 9999', 'Rs. 9999', 'Rs. 8449Rs. 12999', '(35% OFF)', 'Rs. 7999', 'Rs. 9499Rs. 9999', '(5% OFF)', 'Rs. 7499Rs. 9999', '(25% OFF)', 'Rs. 11999Rs. 14999', '(20% OFF)', 'Rs. 7195', 'Rs. 9999', 'Rs. 8074Rs. 8499', '(5% OFF)', 'Rs. 9999', 'Rs. 11999', 'Rs. 9999', 'Rs. 9999', 'Rs. 7999', 'Rs. 8999', 'Rs. 8999', 'Rs. 9999', 'Rs. 8999', 'Rs. 9999', 'Rs. 7799Rs. 12999', '(40% OFF)', 'Rs. 8500Rs. 10500', '(Rs. 2000 OFF)', 'Rs. 7599Rs. 7999', '(5% OFF)', 'Rs. 9999', 'Rs. 7999', 'Rs. 9800Rs. 13900', '(Rs. 4100 OFF)', 'Rs. 12999', 'Rs. 11999', 'Rs. 11900Rs. 13900', '(Rs. 2000 OFF)', 'Rs. 9999', 'Rs. 9810Rs. 10900', '(Rs. 1090 OFF)', 'Rs. 7590Rs. 7990', '(5% OFF)', 'Rs. 10710Rs. 11900', '(Rs. 1190 OFF)', 'Rs. 9990', 'Rs. 7999', 'Rs. 7990', 'Rs. 7219Rs. 7599', '(5% OFF)', 'Rs. 8999', 'Rs. 8990', 'Rs. 8990', 'Rs. 7900Rs. 8900', '(Rs. 1000 OFF)', 'Rs. 7999', 'Rs. 12999', 'Rs. 11899Rs. 16999', '(30% OFF)', 'Rs. 12510Rs. 13900', '(Rs. 1390 OFF)']
69
---------------------------------
Rs. 7195
Rs. 11249Rs. 14999
(25% OFF)
Rs. 13999
Rs. 8295
Rs. 7595Rs. 7995
(5% OFF)
Rs. 9999
Rs. 9999
Rs. 8449Rs. 12999
(35% OFF)
Rs. 7999
Rs. 9499Rs. 9999
(5% OFF)
Rs. 7499Rs. 9999
(25% OFF)
Rs. 11999Rs. 14999
(20% OFF)
Rs. 7195
Rs. 9999
Rs. 8074Rs. 8499
(5% OFF)
Rs. 9999
Rs. 11999
Rs. 9999
Rs. 9999
Rs. 7999
Rs. 8999
Rs. 8999
Rs. 9999
Rs. 8999
Rs. 9999
Rs. 7799Rs. 12999
(40% OFF)
Rs. 8500Rs. 10500
(Rs. 2000 OFF)
Rs. 7599Rs. 7999
(5% OFF)
Rs. 9999
Rs. 7999
Rs. 9800Rs. 13900
(Rs. 4100 OFF)
Rs. 12999
Rs. 11999
Rs. 11900Rs. 13900
(Rs. 2000 OFF)
Rs. 9999
Rs. 9810Rs. 10900
(Rs. 1090 OFF)
Rs. 7590Rs. 7990
(5% OFF)
Rs. 10710Rs. 11900
(Rs. 1190 OFF)
Rs. 9990
Rs. 7999
Rs. 7990
Rs. 7219Rs. 7599
(5% OFF)
Rs. 8999
Rs. 8990
Rs. 8990
Rs. 7900Rs. 8900
(Rs. 1000 OFF)
Rs. 7999
Rs. 12999
Rs. 11899Rs. 16999
(30% OFF)
Rs. 12510Rs. 13900
(Rs. 1390 OFF)

In [203]:
## Taking driver to the specific url on next page:-
driver.get("https://www.myntra.com/shoes?f=Color%3ABlack_36454f&p=2&rf=Price%3A7195.0_14130.0_7195.0%20TO%2014130.0%2C7187.0_14125.0_7187.0%20TO%2014125.0")

In [204]:
## Creating empty lists for Brand,Short Description,and Price.:-
brand2 = []
Short_desc2=[]
price2=[]

## Scrapping Brand on page 2:- 
br2 = driver.find_elements_by_xpath("//h3[@class='product-brand']")
for i in br2:
    brand2.append(i.text)
print("-------------Brand---------------------------")    
print(brand2) 
print(len(brand2))
print("--------------------------------------------------")

## Scrapping Short Description on page 2:- 

sd2 = driver.find_elements_by_xpath("//h4[@class='product-product']")
for i in sd2:
    Short_desc2.append(i.text)
    
print("------------------Short Description------------------")
print(Short_desc2)
print(len(Short_desc2))
print("--------------------------------------------")

## Scrapping Price Data on page2 :-

pp2= driver.find_elements_by_xpath("//div[@class='product-price']/span")
for i in pp2:
    price2.append(i.text)
print("-----------Price-----------------")  
print(price2)
print(len(price2))
print("---------------------------------")

-------------Brand---------------------------
['Puma', 'Saint G', 'Tommy Hilfiger', 'ROSSO BRUNELLO', 'Hush Puppies', 'Saint G', 'ASICS', 'UNDER ARMOUR', 'Puma', 'UNDER ARMOUR', 'Geox', 'Cole Haan', 'Saint G', 'fitflop', 'Puma', 'Geox', 'Onitsuka Tiger', 'ASICS', 'Tommy Hilfiger', 'Bugatti', 'Geox', 'Bugatti', 'Ruosh', 'ASICS', 'J.FONTINI', 'Calvin Klein', 'Nike', 'J.FONTINI', 'Geox', 'Xtep', 'Geox', 'Geox', 'RARE RABBIT', 'Nike', 'RARE RABBIT', 'Calvin Klein', 'J.FONTINI', 'DAVINCHI', 'DAVINCHI', 'DAVINCHI', 'DAVINCHI', 'ADIDAS', 'J.FONTINI', 'DAVINCHI', 'DAVINCHI', 'Pavers England', 'ASICS', 'ADIDAS', 'Saint G', 'Geox']
50
--------------------------------------------------
------------------Short Description------------------
['Men FUTURE 5.1 Football Shoes', 'Women Leather Heeled Boots', 'Women Leather Sneakers', 'Leather High-Top Block Heeled Boots', 'Men Solid Formal Leather Slip-Ons', 'Textured Leather Block Heeled Boots', 'Women Running Shoes', 'Women Charged Vantage ClrShft', 'Women Magnify Nitro Shoes', 'Women Charged Impulse Shft', 'Women Quilted Leather Pumps', 'Women Leather Sneakers', 'Women Leather Heeled Boots', 'Embellished Platform Sandals', 'Men Magnify Nitro Running', 'Women Leather Heeled Loafers', 'Women Perforations Sneakers', 'Men Black Running Sports Shoes', 'Women Hybrid Leather Sneakers', 'Men Black Walking Shoes', 'Men Leather Mid-Top Flat Boots', 'Men Walking Shoes', 'Men Solid Leather Formal Monks', 'Men Running Shoes', 'Men Textured Leather Loafers', 'Men Textured REILAND Sneakers', 'Women Air Zoom Vomero 16 Run', 'Men Solid Loafers', 'Men Leather Formal Derbys', 'Men Running Shoes', 'Men Leather Driving Shoes', 'Men Leather Flat Boots', 'Men Textured Leather Loafers', 'Men AIR ZOOM PEGASUS 36 Shoes', 'Men Leather Flat Boots', 'Men Solid Suede Sneakers', 'Men Black Leather Loafers', 'Ustraa black', 'Solid Slip On Shoes', 'Men Formal Leather Slip-Ons', 'Solid Leather Formal Shoes', 'Women Supernova X Marimekko', 'Men Textured Leather Formal Loafers', 'Men Solid Leather Formal Derbys', 'Men Textured Formal Leather Oxfords', 'Men Leather Driving Shoes', 'Men Black Running Shoes', 'Men Court Jam Bounce Tennis', 'Leather Block Peep Toes', 'Men Leather Formal Derbys']
50
--------------------------------------------
-----------Price-----------------
['Rs. 11899Rs. 16999', '(30% OFF)', 'Rs. 12510Rs. 13900', '(Rs. 1390 OFF)', 'Rs. 7219Rs. 7599', '(5% OFF)', 'Rs. 13999', 'Rs. 9999', 'Rs. 10500Rs. 10900', '(Rs. 400 OFF)', 'Rs. 8999', 'Rs. 7999', 'Rs. 7799Rs. 12999', '(40% OFF)', 'Rs. 7499', 'Rs. 8999', 'Rs. 10999', 'Rs. 7500Rs. 9500', '(Rs. 2000 OFF)', 'Rs. 7499', 'Rs. 9099Rs. 12999', '(30% OFF)', 'Rs. 8999', 'Rs. 8999', 'Rs. 7999', 'Rs. 7599Rs. 7999', '(5% OFF)', 'Rs. 8999', 'Rs. 12999', 'Rs. 8999', 'Rs. 8990', 'Rs. 7999', 'Rs. 7990', 'Rs. 8999', 'Rs. 13495', 'Rs. 8990', 'Rs. 11490', 'Rs. 7699', 'Rs. 9999', 'Rs. 11999', 'Rs. 7699Rs. 10999', '(30% OFF)', 'Rs. 9995', 'Rs. 9999', 'Rs. 7999', 'Rs. 8490', 'Rs. 8990', 'Rs. 7990', 'Rs. 8990', 'Rs. 7990', 'Rs. 11399Rs. 11999', '(5% OFF)', 'Rs. 8990', 'Rs. 8990', 'Rs. 7990', 'Rs. 7499', 'Rs. 9999', 'Rs. 7999', 'Rs. 9450Rs. 10500', '(Rs. 1050 OFF)', 'Rs. 9999']
61
---------------------------------

In [210]:
### Making DataFrame for Shoes data  using colour and price filter from Myntra:-

Brand_100 =[]
short_desc_100=[]
price_100 =[]

## Adding to get 100 shoes's Brand from Myntra:-

Brand_100 = brand1 + brand2
print(len(Brand_100))

## Adding to get 100 shoes's Short description from Myntra:- 

short_desc_100 = Short_desc1 + Short_desc2
print(len(short_desc_100))

## Adding to get 100 shoes's price from Myntra:- 

## Since on page1 price returns 68 list length and on page2 price returns 61 list lengthdata,so making it 50 used slicing 

price_100 = price1[:50] + price2[:50]
print(len(price_100))
shoes_df = pd.DataFrame({ 'Brand': Brand_100,
                         'Short Description': short_desc_100,
                         'price_100' : price_100
    
                        })

shoes_df

100
100
100

             Brand               Short Description           price_100
0             Nike   Men Zoom Span 4 Running Shoes            Rs. 7195
1             Puma  Men Deviate Nitro Running Shoe  Rs. 11249Rs. 14999
2     UNDER ARMOUR        Men HOVR Apex 2 Training           (25% OFF)
3             Nike      Men Waffle One SE Sneakers           Rs. 13999
4             Nike      Men FLIGHT LEGACY Sneakers            Rs. 8295
..             ...                             ...                 ...
95  Pavers England       Men Leather Driving Shoes            Rs. 8490
96           ASICS         Men Black Running Shoes            Rs. 8990
97          ADIDAS     Men Court Jam Bounce Tennis            Rs. 7990
98         Saint G         Leather Block Peep Toes            Rs. 8990
99            Geox       Men Leather Formal Derbys            Rs. 7990

[100 rows x 3 columns]

In [228]:
driver.close()

# 8.Scrapping Data for laptops CPU Type intel i7 on Amazon

In [46]:
## Instatiating chrome driver
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [47]:
## Taking driver to the specific url:-
#driver.get("https://www.amazon.in/s?k=laptop&rh=n%3A1375424031%2Cp_n_feature_thirteen_browse-bin%3A12598163031&dc&qid=1639394772&rnid=12598141031&ref=sr_nr_p_n_feature_thirteen_browse-bin_10")
driver.get("https://www.amazon.in/")

In [48]:
## Xpath for Search:-
search_prd = driver.find_element_by_xpath("//input[@class='nav-input nav-progressive-attribute']")
search_prd.send_keys('Laptop')

In [50]:
## xpath for clicking search:-
search_click = driver.find_element_by_xpath("//div[@class='nav-search-submit nav-sprite']")
search_click.click()

In [65]:
## for cpu type i7 xpath:-
#rom selenium import WebElement
driver.get("https://www.amazon.in/s?k=Laptop&rh=n%3A1375424031%2Cp_n_feature_thirteen_browse-bin%3A12598163031&dc&qid=1639636121&rnid=12598141031&ref=sr_nr_p_n_feature_thirteen_browse-bin_12")

In [98]:
## Making empty lists for Title,ratings and Price :-
title =[]
ratings =[]
price =[]

#### Scrapping title data for laptop cpu type i7:-
title_tags = driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in title_tags:
    title.append(i.text)
print(title[:10]) 
print(len(title[:10]))

### Scrapping ratings data for Laptop cpu type i7:-
rat_link = driver.find_elements_by_xpath("//div[@class='a-section a-spacing-none a-spacing-top-micro']//div[@class='a-row a-size-small']/span")
 
#print(rat.get_attribute('aria-label'))
# for i in rat:
#     ratings.append(i.get_attribute('aria-label'))
# print(ratings)
for rating in rat_link:
    ratings.append(rating.get_attribute('aria-label'))
print(ratings[0:20:2])    


pp = driver.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in pp:
    price.append(i.text)
print(price[:10])    

#### Making dataframe:-
laptop_df = pd.DataFrame({'Title':title[:10],
                          'Rating':ratings[0:20:2],
                          'Price':price[:10]
    
                         })
laptop_df

['Fujitsu UH-X 11th Gen Intel i7 Core 13.3 inches FHD IPS 400Nits Thin and Light Business Laptop (16GB/512GB SSD/Windows 10/Office/Iris Xe Graphics/Backlit Kb/ Fingerprint Reader/Black/0.878kg), 4ZR1D67596', 'Acer Nitro 5 AN515-57 Gaming Laptop | Intel Core i7-11800H |NVIDIA GeForce RTX 3050 Laptop Graphics |15.6" FHD 144Hz IPS Display |8GB DDR4 | 256GB SSD+1TB HDD | Killer Wi-Fi 6 | RGB Backlit Keyboard', 'Mi Notebook Pro QHD+ IPS Anti Glare Display Intel Core i7-11370H 11th Gen 14-inch(35.56 cms) Thin and Light Laptop (16GB/512GB SSD/Iris Xe Graphics/Win 10/Backlit KB/Fingerprint Sensor/1.4 Kg)', 'Mi Notebook Horizon Edition 14 Intel Core i7-10510U 10th Gen Thin and Light Laptop(8GB/512GB SSD/Windows 10/Nvidia MX350 2GB Graphics/Grey/1.35Kg)(Without Webcam) XMA1904-AF', 'HP Pavilion (2021) Intel 11th Gen Core i7 14 inches FHD Screen Thin & Light Laptop, 16 GB RAM, 1TB SSD, Iris Xe Graphics, Windows 10, MS Office, Backlit Keyboard, 1.41kg (14-dv0058TU)', 'MSI GF75 Thin, Intel i7-10750H, 17.3" (43.9 cm) FHD IPS-Level 144Hz Panel Laptop (8GB/512GB NVMe SSD/Windows 10 Home/Nvidia GTX1650 4GB GDDR6/Black/2.2Kg), 10SCXR-654IN', 'ASUS TUF Dash F15 (2021) 15.6-inch (39.62 cms) FHD 144Hz, Intel Core i7-11370H 11th Gen, RTX 3060 6GB Graphics, Gaming Laptop (16GB/512GB SSD/Office 2019/Windows 10/Gray/2 Kg), FX516PM-HN175TS', 'ASUS TUF Dash F15 (2021) 15.6" (39.62 cm) FHD 240Hz/3ms, Intel Core i7-11370H, GeForce RTX 3060 6GB Graphics, Gaming Laptop (16GB RAM/1TB SSD/Office 2019/Windows 10 Home/Gray/2 Kg) FX516PM-AZ153TS', 'Lenovo Legion 5 11th Gen Intel Core i7 15.6"(39.62cm) FHD IPS Gaming Laptop (16GB/512GB SSD/NVIDIA RTX 3050 4GB/120Hz Refresh Rate/Windows 10/MS Office/Backlit Keyboard/Phantom Blue/2.4Kg), 82JK007WIN', 'HP Pavilion Gaming(2021) 10th Gen Intel Core i7 15.6-inch(39.6 cm) FHD IPS 144Hz Gaming Laptop (16GB/512GB SSD + 32GB Intel Optane/NVIDIA GTX 1650Ti 4GB/Win 10/MS Office/Shadow Black), 15-DK1511TX']
10
['4.3 out of 5 stars', '4.1 out of 5 stars', '4.3 out of 5 stars', '4.2 out of 5 stars', '4.3 out of 5 stars', '4.4 out of 5 stars', '4.4 out of 5 stars', '4.2 out of 5 stars', '4.4 out of 5 stars', '4.1 out of 5 stars']
['92,990', '88,990', '72,999', '49,990', '84,990', '72,990', '1,09,990', '1,24,990', '1,00,990', '86,990']

,Title,Rating,Price
0,Fujitsu UH-X 11th Gen Intel i7 Core 13.3 inche...,4.3 out of 5 stars,"92,990"
1,Acer Nitro 5 AN515-57 Gaming Laptop | Intel Co...,4.1 out of 5 stars,"88,990"
2,Mi Notebook Pro QHD+ IPS Anti Glare Display In...,4.3 out of 5 stars,"72,999"
3,Mi Notebook Horizon Edition 14 Intel Core i7-1...,4.2 out of 5 stars,"49,990"
4,HP Pavilion (2021) Intel 11th Gen Core i7 14 i...,4.3 out of 5 stars,"84,990"
5,"MSI GF75 Thin, Intel i7-10750H, 17.3"" (43.9 cm...",4.4 out of 5 stars,"72,990"
6,ASUS TUF Dash F15 (2021) 15.6-inch (39.62 cms)...,4.4 out of 5 stars,"1,09,990"
7,"ASUS TUF Dash F15 (2021) 15.6"" (39.62 cm) FHD ...",4.2 out of 5 stars,"1,24,990"
8,"Lenovo Legion 5 11th Gen Intel Core i7 15.6""(3...",4.4 out of 5 stars,"1,00,990"
9,HP Pavilion Gaming(2021) 10th Gen Intel Core i...,4.1 out of 5 stars,"86,990"

# Scrapping for i9 cpu type:-

In [99]:
### After applying filter for i9 cpu type:-
driver.get("https://www.amazon.in/s?k=Laptop&rh=n%3A1375424031%2Cp_n_feature_thirteen_browse-bin%3A16757432031&dc&qid=1639635820&rnid=12598141031&ref=sr_nr_p_n_feature_thirteen_browse-bin_13")

In [107]:
## Making empty lists for Title,ratings and Price :-
title =[]
ratings =[]
price =[]

#### Scrapping title data for laptop cpu type i7:-
title_tags = driver.find_elements_by_xpath("//span[@class='a-size-medium a-color-base a-text-normal']")
for i in title_tags:
    title.append(i.text)
print(title[:12]) 
print(len(title[:12]))

### Scrapping ratings data for Laptop cpu type i7:-
rat_link = driver.find_elements_by_xpath("//div[@class='a-section a-spacing-none a-spacing-top-micro']//div[@class='a-row a-size-small']/span")
 
#print(rat.get_attribute('aria-label'))
# for i in rat:
#     ratings.append(i.get_attribute('aria-label'))
# print(ratings)
for rating in rat_link:
    ratings.append(rating.get_attribute('aria-label'))
print(ratings)  
print(len(ratings))


pp = driver.find_elements_by_xpath("//span[@class='a-price-whole']")
for i in pp:
    price.append(i.text)
print(price)  
print(len(price))

#### Making dataframe:-

### Since only for some  products rating are not given and only 8 products are shown for i9,so making dataframe for 4 products omly.
laptop_df = pd.DataFrame({'Title':title[:4],
                          'Rating':ratings[:8:2],
                          'Price':price[:4]
    
                         })
laptop_df

['ASUS TUF Gaming F15 (2021), 15.6-inch (39.62 cms) FHD 240Hz/3ms, Intel Core i9-11900H 11th Gen, RTX 3060 6GB Graphics Gaming Laptop (16GB/1TB SSD/Office 2019/Windows 10/Black/2.3 kg), FX506HM-AZ099TS', 'ASUS ROG Strix Scar III G531GW 15.6" FHD 240Hz Gaming Laptop RTX 2070 8GB Graphics (Core i9-9880H 9th Gen/32GB RAM/1TB PCIe SSD/Windows 10/Scar Gunmetal/2.57 Kg), G531GW-AZ113T', 'Lenovo Legion 7 10th Gen Intel Core i9 15.6 inch Full HD Gaming Laptop (16GB/1TB SSD/Windows 10/MS Office 2019/144 Hz/NVIDIA RTX 2080 8GB GDDR6 Graphics/Slate Grey/2.25Kg), 81YU006HIN', '(Renewed) Dell G7 7500 15.6inch FHD 300 Hz Display Gaming Laptop (10th Gen i9-10885H / 16 GB / 1TB SSD / NVIDIA RTX 2070 8GB Graphics / 1Yr Premium Warranty / Win 10 + MS Office H&S 2019) D560233WIN9B, Black', 'Dell XPS 7590 39.62 cm (15.6-inch) UHD Display Laptop (9th Gen Core i9-9980HK/32GB/1TB SSD/Win 10 + MS Office/4GB Nvidia Graphics), Abyss Grey', 'Dell XPS 17 (2021) i9-11900H Touch Screen Laptop / 32GB / 1TB SSD/ NVIDIA RTX 3060 6GB GDDR6 / Win 10 + MS Office/ 17.0" UHD+ AR 500 nits / Backlit KB + FPR / Platinum Silver (XPS 9710, D560057WIN9S)', 'HP ZBOOK Power G8/ Intel core i9-11900H 8 Core/32GB DDR4 3200 RAM/1TB PCIe NVMe TLC SSD /15.6” FHD /Nvidia Quadro T1200 Dedicated Graphics 4GB DDR6 /Windows 10 Pro / 3 Year Warranty', 'Z2 G5 Workstation 700W /Core i9-10900 (2.8GHz 10C) /16GB RAM/512GB SSD+1TB SATA/Nvidia RTX 3070 8GB Graphics/DVDRW/Windows 10 Pro/3 Year Warranty']
8
['3.8 out of 5 stars', '5', '5.0 out of 5 stars', '2', '4.4 out of 5 stars', '10', '3.8 out of 5 stars', '14']
8
['1,49,300', '2,65,999', '2,25,000', '2,01,900', '3,75,000', '2,45,000', '2,39,000', '359.', '8,999.', '399.', '1,049.', '625.']
12

,Title,Rating,Price
0,"ASUS TUF Gaming F15 (2021), 15.6-inch (39.62 c...",3.8 out of 5 stars,"1,49,300"
1,"ASUS ROG Strix Scar III G531GW 15.6"" FHD 240Hz...",5.0 out of 5 stars,"2,65,999"
2,Lenovo Legion 7 10th Gen Intel Core i9 15.6 in...,4.4 out of 5 stars,"2,25,000"
3,(Renewed) Dell G7 7500 15.6inch FHD 300 Hz Dis...,3.8 out of 5 stars,"2,01,900"

In [108]:
driver.close()

# 9.Scrapping Data Scientist data for location Noida:-

In [109]:
## Instatiating chrome driver
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [110]:
## Taking driver to the specific url:-
driver.get("https://www.ambitionbox.com/jobs/search?tag=Data%20Scientist&location=Noida")

In [282]:
### Making empty lists for Company Name,No of days ago,and rating:-
company =[]
days =[]
rating=[]
## Scrapping data for Company Name:-
comp = driver.find_elements_by_xpath("//p[@class='company body-medium']")
for i in comp:
    company.append(i.text)
print(company) 
print(len(company))

## Scrapping data for Days ago post:-
days_ago = driver.find_elements_by_xpath("//span[@class='body-small-l']")
for i in days_ago:
    days.append(i.text)
print(days[::2])  
print(len(days[::2]))

##  Scrapping Rating:-
rate = driver.find_elements_by_xpath("//span[@class='body-small']")
for i in rate:
    rating.append(i.text)
print(rating) 

### Making Data Frame:-
ds_df = pd.DataFrame({'Company Name':company,
                      'Post dated' :days[::2],
                       'Rating':rating
                       })
ds_df

['LG Electronics India Pvt. Ltd.', 'GENPACT India Private Limited', 'GENPACT India Private Limited', '', '', '', '', '', '', '']
10
['3d ago', '10d ago', '', '', '', '', '', '', '', '']
10
['4.1', '4.0', '4.0', '', '', '', '', '', '', '']

                     Company Name Post dated Rating
0  LG Electronics India Pvt. Ltd.     3d ago    4.1
1   GENPACT India Private Limited    10d ago    4.0
2   GENPACT India Private Limited               4.0
3
4
5
6
7
8
9

In [111]:
driver.close()

# 10.Scrapping Data for Company Name,Total Salary Record,Minimum ,Maximum and Average Salary and experience record

In [90]:
## Instatiating chrome driver
driver = webdriver.Chrome(r"C:/Users/swati/Downloads/chromedriver_win32/chromedriver.exe")

In [91]:
driver.get("https://www.ambitionbox.com/profile/data-scientist-salary")

In [92]:
## making empty lists for Company name, Total salary record,min salary,average salary,max salary and experience required:-

name =[]
total_salary=[]
min_salary =[]
max_salary =[]
avg_salary =[]
exp =[]

## Scrapping Company Name:
company = driver.find_elements_by_xpath("//div[@class='name']/a")
for i in company:
    name.append(i.text)
print("------------Company Name-------------------------")    
print(name)
print("------------------------------------------------")
## Since list has returned elements with single inverted comma,so using translate method removing it.
## For this ascii code of "'" i.e;39 is set to None.
target = {39:None}
print(str(name).translate(target))   
## Scrapping Total salary record:
t_salary = driver.find_elements_by_xpath("//div[@class='name']/span")
for i in t_salary:
    total_salary.append(i.text)
print("--------------Total Salary Record---------------------------")    
print(total_salary)   
###Removing small braces from Total Salary list using translate method.Since it is a string method so type casted total_salary into 
## string and then use ascii code for "'" that is 39, 40 for "(" and 41 for ") " and set it to none and then translate.

target ={39 : None,40 : None, 41 : None}
total_sal_rec =str(total_salary).translate(target)
print(total_sal_rec)

print("---------------------------------------------------------------")


### Scrappin min salary:-
#salary = driver.find_elements_by_id("//div[@class='result-col salary-range'")
m_salary = driver.find_elements_by_xpath("//div[@class='result-col salary-range']//div[@class='salary-values']//div[1]")

for i in m_salary:
    min_salary.append(i.text)
print("------------Minimum Salary----------------")    
print(min_salary)

## Since list has returned elements with single inverted comma,so using translate method removing it.
## For this ascii code of "'" i.e;39 is set to None.
print("------After removing single inverted comma-----------------")
target = {39:None}
print(str(min_salary).translate(target))   

ma_salary = driver.find_elements_by_xpath("//div[@class='result-col salary-range']//div[@class='salary-values']//div[2]")
for i in ma_salary:
    max_salary.append(i.text)
print(max_salary)   
## Since list has returned elements with single inverted comma,so using translate method removing it.
## For this ascii code of "'" i.e;39 is set to None.
print("------After removing single inverted comma-----------------")

target = {39:None}
print(str(max_salary).translate(target))   
print("-----------------------------")

av_salary = driver.find_elements_by_xpath("//div[@class='average-indicator-wrapper']//p[@class='averageCtc']")
for i in av_salary:
    avg_salary.append(i.text)
print(avg_salary[9:])   

## Since list has returned elements with single inverted comma,so using translate method removing it.
## For this ascii code of "'" i.e;39 is set to None.

print("------After removing single inverted comma-----------------")

target = {39:None}

print(str(avg_salary[9:]).translate(target))   
print("-----------------------------")

exp_req = driver.find_elements_by_xpath("//div[@class='salaries one-line sbold-list-header']/span")
for i in exp_req:
    exp.append(i.text)
print(exp) 

## Since list has returned elements with single inverted comma,so using translate method removing it.
## For this ascii code of "'" i.e;39 is set to None.

print("------After removing single inverted comma-----------------")

target = {39:None}
print(str(exp).translate(target))   
print("-----------------------------")

### Finally making dataframe:-
salary_df = pd.DataFrame({'Company Name':name,
                          'Total salary record':total_salary,
                          'Min Salary':min_salary,
                          'Max Salary':max_salary,
                          'Avg Salary':avg_salary[9:],
                           'Experience':exp
                          
    
                         })
salary_df

------------Company Name-------------------------
['TCS', 'Accenture', 'IBM', 'Cognizant', 'Capgemini', 'Tech Mahindra', 'Infosys', 'Wipro', 'Ericsson', 'HCL Technologies']
------------------------------------------------
[TCS, Accenture, IBM, Cognizant, Capgemini, Tech Mahindra, Infosys, Wipro, Ericsson, HCL Technologies]
--------------Total Salary Record---------------------------
['(619 Salaries)', '(375 Salaries)', '(301 Salaries)', '(242 Salaries)', '(225 Salaries)', '(187 Salaries)', '(173 Salaries)', '(170 Salaries)', '(125 Salaries)', '(124 Salaries)']
[619 Salaries, 375 Salaries, 301 Salaries, 242 Salaries, 225 Salaries, 187 Salaries, 173 Salaries, 170 Salaries, 125 Salaries, 124 Salaries]
---------------------------------------------------------------
------------Minimum Salary----------------
['₹ 4.4L', '₹ 5.4L', '₹ 5.0L', '₹ 5.0L', '₹ 4.6L', '₹ 4.2L', '₹ 4.5L', '₹ 4.3L', '₹ 5.2L', '₹ 4.5L']
------After removing single inverted comma-----------------
[₹ 4.4L, ₹ 5.4L, ₹ 5.0L, ₹ 5.0L, ₹ 4.6L, ₹ 4.2L, ₹ 4.5L, ₹ 4.3L, ₹ 5.2L, ₹ 4.5L]
['₹ 15.0L', '₹ 22.0L', '₹ 23.0L', '₹ 16.5L', '₹ 14.0L', '₹ 16.4L', '₹ 21.0L', '₹ 18.0L', '₹ 26.0L', '₹ 20.0L']
------After removing single inverted comma-----------------
[₹ 15.0L, ₹ 22.0L, ₹ 23.0L, ₹ 16.5L, ₹ 14.0L, ₹ 16.4L, ₹ 21.0L, ₹ 18.0L, ₹ 26.0L, ₹ 20.0L]
-----------------------------
['₹ 7.4L', '₹ 11.8L', '₹ 11.7L', '₹ 9.3L', '₹ 8.1L', '₹ 7.8L', '₹ 8.6L', '₹ 9.4L', '₹ 13.4L', '₹ 9.4L']
------After removing single inverted comma-----------------
[₹ 7.4L, ₹ 11.8L, ₹ 11.7L, ₹ 9.3L, ₹ 8.1L, ₹ 7.8L, ₹ 8.6L, ₹ 9.4L, ₹ 13.4L, ₹ 9.4L]
-----------------------------
['2-9 yrs exp', '2-9 yrs exp', '2-12 yrs exp', '2-11 yrs exp', '2-7 yrs exp', '2-13 yrs exp', '2-8 yrs exp', '2-9 yrs exp', '2-12 yrs exp', '2-10 yrs exp']
------After removing single inverted comma-----------------
[2-9 yrs exp, 2-9 yrs exp, 2-12 yrs exp, 2-11 yrs exp, 2-7 yrs exp, 2-13 yrs exp, 2-8 yrs exp, 2-9 yrs exp, 2-12 yrs exp, 2-10 yrs exp]
-----------------------------

,Company Name,Total salary record,Min Salary,Max Salary,Avg Salary,Experience
0,TCS,(619 Salaries),₹ 4.4L,₹ 15.0L,₹ 7.4L,2-9 yrs exp
1,Accenture,(375 Salaries),₹ 5.4L,₹ 22.0L,₹ 11.8L,2-9 yrs exp
2,IBM,(301 Salaries),₹ 5.0L,₹ 23.0L,₹ 11.7L,2-12 yrs exp
3,Cognizant,(242 Salaries),₹ 5.0L,₹ 16.5L,₹ 9.3L,2-11 yrs exp
4,Capgemini,(225 Salaries),₹ 4.6L,₹ 14.0L,₹ 8.1L,2-7 yrs exp
5,Tech Mahindra,(187 Salaries),₹ 4.2L,₹ 16.4L,₹ 7.8L,2-13 yrs exp
6,Infosys,(173 Salaries),₹ 4.5L,₹ 21.0L,₹ 8.6L,2-8 yrs exp
7,Wipro,(170 Salaries),₹ 4.3L,₹ 18.0L,₹ 9.4L,2-9 yrs exp
8,Ericsson,(125 Salaries),₹ 5.2L,₹ 26.0L,₹ 13.4L,2-12 yrs exp
9,HCL Technologies,(124 Salaries),₹ 4.5L,₹ 20.0L,₹ 9.4L,2-10 yrs exp

In [93]:
driver.close()